package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

const componentPrefix = "github.com/grafana/alloy/internal/component/"

// testComponentPackages stands in for the output of the componentpkgs helper,
// which compiles every component and is too slow for most tests. Note that
// some packages register several components.
var testComponentPackages = map[string]string{
	"discovery.aws":       componentPrefix + "discovery/aws",
	"discovery.ec2":       componentPrefix + "discovery/aws",
	"discovery.lightsail": componentPrefix + "discovery/aws",
	"local.file_match":    componentPrefix + "local/file_match",
	"loki.process":        componentPrefix + "loki/process",
	"loki.relabel":        componentPrefix + "loki/relabel",
	"loki.source.file":    componentPrefix + "loki/source/file",
	"loki.write":          componentPrefix + "loki/write",
	"prometheus.scrape":   componentPrefix + "prometheus/scrape",
}

// ocbMainFile is a trimmed down version of the main.go generated by OCB. It
// contains the lines which the generator rewrites.
const ocbMainFile = `package main

func main() {
	info := component.BuildInfo{
		Command:     "alloy",
		Description: "Alloy OTel Collector distribution.",
		Version:     "1.20.0",
	}
}

func runInteractive(params otelcol.CollectorSettings) error {
	cmd := otelcol.NewCommand(params)
	return cmd.Execute()
}
`

// otelComponents is a builder config fragment with OTel Collector components.
const otelComponents = `
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.161.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.161.0
`

func TestGenerate_ComponentsAlloy(t *testing.T) {
	tests := []struct {
		name   string
		config string
		// expect is the expected content of components_alloy.go.
		expect string
	}{
		{
			name:   "no alloy section includes everything",
			config: otelComponents,
			expect: `// GENERATED CODE: DO NOT EDIT

package main

// Native Alloy components and features selected in the "alloy" section of builder-config.yaml.
import (
	_ "github.com/grafana/alloy/internal/component/all"
	_ "github.com/grafana/alloy/internal/converter/enable"
)
`,
		},
		{
			name: "all components without converters",
			config: `
alloy:
  components: all
  converters: false
` + otelComponents,
			expect: `// GENERATED CODE: DO NOT EDIT

package main

// Native Alloy components and features selected in the "alloy" section of builder-config.yaml.
import (
	_ "github.com/grafana/alloy/internal/component/all"
)
`,
		},
		{
			name: "list of loki components",
			config: `
alloy:
  components: [loki.write, loki.source.file, loki.relabel, loki.process]
  converters: false
` + otelComponents,
			// Imports are sorted by package, not by the order in the config.
			expect: `// GENERATED CODE: DO NOT EDIT

package main

// Native Alloy components and features selected in the "alloy" section of builder-config.yaml.
import (
	_ "github.com/grafana/alloy/internal/component/loki/process"
	_ "github.com/grafana/alloy/internal/component/loki/relabel"
	_ "github.com/grafana/alloy/internal/component/loki/source/file"
	_ "github.com/grafana/alloy/internal/component/loki/write"
)
`,
		},
		{
			name: "converters default to enabled",
			config: `
alloy:
  components: [prometheus.scrape]
` + otelComponents,
			expect: `// GENERATED CODE: DO NOT EDIT

package main

// Native Alloy components and features selected in the "alloy" section of builder-config.yaml.
import (
	_ "github.com/grafana/alloy/internal/component/prometheus/scrape"
	_ "github.com/grafana/alloy/internal/converter/enable"
)
`,
		},
		{
			name: "components registered by the same package are imported once",
			config: `
alloy:
  components: [discovery.ec2, discovery.aws, discovery.lightsail, discovery.ec2]
  converters: false
` + otelComponents,
			expect: `// GENERATED CODE: DO NOT EDIT

package main

// Native Alloy components and features selected in the "alloy" section of builder-config.yaml.
import (
	_ "github.com/grafana/alloy/internal/component/discovery/aws"
)
`,
		},
		{
			name: "no components and no converters",
			config: `
alloy:
  components: []
  converters: false
` + otelComponents,
			expect: `// GENERATED CODE: DO NOT EDIT

package main
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := runGenerate(t, tt.config)
			require.Equal(t, tt.expect, readFile(t, dir, "components_alloy.go"))
		})
	}
}

func TestGenerate_WithOTelEngine(t *testing.T) {
	dir := runGenerate(t, `
alloy:
  components: [loki.source.file, loki.write]
`+otelComponents)

	// The OCB main.go is rewritten to run the Alloy CLI with the OTel Engine
	// as a subcommand.
	main := readFile(t, dir, "main.go")
	require.Contains(t, main, "cmd := newAlloyCommand(params)")
	require.Contains(t, main, "Version:     CollectorVersion(),")
	require.NotContains(t, main, "otelcol.NewCommand")

	require.Contains(t, readFile(t, dir, "main_alloy.go"), "func newAlloyCommand(")
	require.Contains(t, readFile(t, dir, "main_alloy.go"), "otelsupervisor.NewCommand()")
	require.Contains(t, readFile(t, dir, "main_windows.go"), "//go:build windows")
}

func TestGenerate_WithoutOTelEngine(t *testing.T) {
	tests := []struct {
		name   string
		config string
	}{
		{
			name: "alloy section without OTel components",
			config: `
alloy:
  components: [loki.source.file, loki.process, loki.write]
  converters: false
`,
		},
		{
			name: "empty alloy section",
			config: `
alloy:
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := runGenerate(t, tt.config)

			require.Equal(t, `// GENERATED CODE: DO NOT EDIT

// Program alloy is Grafana Alloy built without the OTel Engine.
package main

import (
	"os"

	"github.com/grafana/alloy/flowcmd"
)

func main() {
	if err := flowcmd.RootCommand().Execute(); err != nil {
		os.Exit(1)
	}
}
`, readFile(t, dir, "main.go"))

			// Files which would import the OTel Engine are emptied.
			for _, name := range []string{"components.go", "main_alloy.go", "main_others.go", "main_windows.go"} {
				require.Equal(t, `// GENERATED CODE: DO NOT EDIT

// Alloy is built without the OTel Engine, so this file is intentionally empty.

package main
`, readFile(t, dir, name), name)
			}
		})
	}
}

func TestGenerate_Errors(t *testing.T) {
	tests := []struct {
		name      string
		config    string
		expectErr string
	}{
		{
			name: "unknown component",
			config: `
alloy:
  components: [loki.write, loki.source.fil, prometheus.scrap, foo.bar]
`,
			expectErr: `unknown components in alloy.components:
  "loki.source.fil" (components in the "loki" namespace: loki.process, loki.relabel, loki.source.file, loki.write)
  "prometheus.scrap" (components in the "prometheus" namespace: prometheus.scrape)
  "foo.bar"`,
		},
		{
			name: "components is a string other than all",
			config: `
alloy:
  components: loki.write
`,
			expectErr: `alloy.components must be "all" or a list of component names, got "loki.write"`,
		},
		{
			name: "components is a map",
			config: `
alloy:
  components:
    loki.write: true
`,
			expectErr: `alloy.components must be "all" or a list of component names`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := setupOCBOutput(t, tt.config)
			err := generate(dir, filepath.Join(dir, "builder-config.yaml"))
			require.ErrorContains(t, err, tt.expectErr)
		})
	}
}

// TestKnownComponentPackages runs the real componentpkgs helper. It compiles
// every native Alloy component, so it is skipped in short mode.
func TestKnownComponentPackages(t *testing.T) {
	if testing.Short() {
		t.Skip("compiles every Alloy component")
	}

	known, err := knownComponentPackages()
	require.NoError(t, err)

	require.Equal(t, componentPrefix+"loki/source/file", known["loki.source.file"])
	require.Equal(t, componentPrefix+"prometheus/remotewrite", known["prometheus.remote_write"])
	require.Equal(t, componentPrefix+"discovery/aws", known["discovery.ec2"])
	for name, pkg := range known {
		require.True(t, strings.HasPrefix(pkg, componentPrefix), "%s is registered by unexpected package %s", name, pkg)
	}
}

// runGenerate runs the generator against a fake OCB output directory and
// returns its path.
func runGenerate(t *testing.T, config string) string {
	t.Helper()

	dir := setupOCBOutput(t, config)
	require.NoError(t, generate(dir, filepath.Join(dir, "builder-config.yaml")))
	return dir
}

// setupOCBOutput creates a directory which looks like OCB output, with the
// given builder config.
func setupOCBOutput(t *testing.T, config string) string {
	t.Helper()

	lookup := lookupComponentPackages
	lookupComponentPackages = func() (map[string]string, error) { return testComponentPackages, nil }
	t.Cleanup(func() { lookupComponentPackages = lookup })

	dir := t.TempDir()
	files := map[string]string{
		"builder-config.yaml": config,
		"main.go":             ocbMainFile,
		"components.go":       "package main\n",
		"main_others.go":      "package main\n",
		"main_windows.go":     "package main\n",
	}
	for name, content := range files {
		require.NoError(t, os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644))
	}
	return dir
}

func readFile(t *testing.T, dir, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, name))
	require.NoError(t, err)
	return string(data)
}
