package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"

	"github.com/grafana/alloy/internal/build"
	"github.com/grafana/alloy/internal/service/graphql/graph/model"
)

// Alloy is the resolver for the alloy field.
func (r *queryResolver) Alloy(ctx context.Context) (model.Alloy, error) {
	return model.Alloy{
		Version:   build.Version,
		Revision:  build.Revision,
		Branch:    build.Branch,
		BuildUser: build.BuildUser,
		BuildDate: build.BuildDate,
	}, nil
}
