package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/grafana/alloy/internal/build"
	"github.com/grafana/alloy/internal/service/graphql/graph/model"
)

// Alloy is the resolver for the alloy field.
func (r *queryResolver) Alloy(ctx context.Context) (model.Alloy, error) {
	return model.NewAlloy(
		model.Alloy{
			Branch:    build.Branch,
			BuildDate: build.BuildDate,
			BuildUser: build.BuildUser,
			Revision:  build.Revision,
			Version:   build.Version,
		},
		r.Host,
	), nil
}
