package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/grafana/alloy/internal/service/graphql/graph/model"
	graphqlservices "github.com/grafana/alloy/internal/service/graphql/services"
)

// Cluster is the resolver for the cluster field.
func (r *queryResolver) Cluster(ctx context.Context) (*model.Cluster, error) {
	return graphqlservices.Cluster(r.Host)
}
