package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/grafana/alloy/internal/service/graphql/graph/model"
	"github.com/grafana/alloy/internal/service/graphql/utils"
)

// Arguments is the resolver for the arguments field.
func (r *componentResolver) Arguments(ctx context.Context, obj *model.Component) (string, error) {
	return utils.MarshalBodyToString(obj.ComponentInfo.Arguments), nil
}

// Exports is the resolver for the exports field.
func (r *componentResolver) Exports(ctx context.Context, obj *model.Component) (string, error) {
	return utils.MarshalBodyToString(obj.ComponentInfo.Exports), nil
}

// DebugInfo is the resolver for the debugInfo field.
func (r *componentResolver) DebugInfo(ctx context.Context, obj *model.Component) (string, error) {
	return utils.MarshalBodyToString(obj.ComponentInfo.DebugInfo), nil
}

// Components is the resolver for the components field.
func (r *queryResolver) Components(ctx context.Context) ([]model.Component, error) {
	allComponents, err := utils.GetAllComponents(r.Host)
	if err != nil {
		return nil, err
	}

	result := make([]model.Component, len(allComponents))
	for i, comp := range allComponents {
		result[i] = model.NewComponent(comp)
	}

	return result, nil
}

// Component is the resolver for the component field.
func (r *queryResolver) Component(ctx context.Context, id string) (*model.Component, error) {
	comp, err := utils.GetComponentByID(r.Host, id)
	if err != nil {
		return nil, err
	}
	result := model.NewComponent(comp)
	return &result, nil
}

// Component returns ComponentResolver implementation.
func (r *Resolver) Component() ComponentResolver { return &componentResolver{r} }

type componentResolver struct{ *Resolver }
