package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/grafana/alloy/internal/service/graphql/graph/model"
	graphqlruntime "github.com/grafana/alloy/internal/service/graphql/runtime"
)

// ParentModule is the resolver for the parentModule field.
func (r *moduleResolver) ParentModule(ctx context.Context, obj *model.Module) (*model.Module, error) {
	if obj.RuntimeGraph == nil || obj.ParentModuleID == nil {
		return nil, nil
	}
	return obj.RuntimeGraph.Module(*obj.ParentModuleID), nil
}

// CreatedBy is the resolver for the createdBy field.
func (r *moduleResolver) CreatedBy(ctx context.Context, obj *model.Module) (*model.Component, error) {
	if obj.RuntimeGraph == nil || obj.CreatedByComponentID == nil {
		return nil, nil
	}
	return obj.RuntimeGraph.Component(*obj.CreatedByComponentID), nil
}

// ChildModules is the resolver for the childModules field.
func (r *moduleResolver) ChildModules(ctx context.Context, obj *model.Module) ([]model.Module, error) {
	if obj.RuntimeGraph == nil {
		return nil, nil
	}
	return obj.RuntimeGraph.ModulesByID(obj.ChildModuleIDs), nil
}

// Components is the resolver for the components field.
func (r *moduleResolver) Components(ctx context.Context, obj *model.Module) ([]model.Component, error) {
	if obj.RuntimeGraph == nil {
		return nil, nil
	}
	return obj.RuntimeGraph.ComponentsByID(obj.ComponentIDs), nil
}

// Modules is the resolver for the modules field.
func (r *queryResolver) Modules(ctx context.Context) ([]model.Module, error) {
	runtimeGraph, err := graphqlruntime.LoadGraph(r.Host, componentInfoOptions)
	if err != nil {
		return nil, err
	}
	return runtimeGraph.Modules(), nil
}

// Module is the resolver for the module field.
func (r *queryResolver) Module(ctx context.Context, id string) (*model.Module, error) {
	runtimeGraph, err := graphqlruntime.LoadGraph(r.Host, componentInfoOptions)
	if err != nil {
		return nil, err
	}
	return runtimeGraph.Module(id), nil
}

// Module returns ModuleResolver implementation.
func (r *Resolver) Module() ModuleResolver { return &moduleResolver{r} }

type moduleResolver struct{ *Resolver }
