package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/grafana/alloy/internal/service/graphql/graph/model"
	graphqlservices "github.com/grafana/alloy/internal/service/graphql/services"
)

// ComponentHTTPPath is the resolver for the componentHTTPPath field.
func (r *hTTPServiceResolver) ComponentHTTPPath(ctx context.Context, obj *model.HTTPService, componentID string) (string, error) {
	return graphqlservices.ComponentHTTPPath(obj, componentID), nil
}

// Services is the resolver for the services field.
func (r *queryResolver) Services(ctx context.Context) ([]model.AlloyService, error) {
	return graphqlservices.Services(r.Host, r.ServiceList), nil
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, name string) (model.AlloyService, error) {
	return graphqlservices.Service(r.Host, r.ServiceList, name), nil
}

// HTTPService returns HTTPServiceResolver implementation.
func (r *Resolver) HTTPService() HTTPServiceResolver { return &hTTPServiceResolver{r} }

type hTTPServiceResolver struct{ *Resolver }
