services:
  mimir:
    image: grafana/mimir:2.12.0
    restart: on-failure
    command:
      - -config.file=/etc/mimir-config/mimir.yaml
    volumes:
      - ./config/mimir:/etc/mimir-config
    ports:
      - "9009:9009"

  loki:
    image: grafana/loki:3.0.0
    restart: on-failure
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:2.4.1
    restart: on-failure
    command:
      - "-storage.trace.backend=local"                  # tell tempo where to permanently put traces
      - "-storage.trace.local.path=/tmp/tempo/traces"
      - "-storage.trace.wal.path=/tmp/tempo/wal"        # tell tempo where to store the wal
      - "-auth.enabled=false"                           # disables the requirement for the X-Scope-OrgID header
      - "-server.http-listen-port=3200"
    ports:
      - "3200:3200"
      - "4317:4317"

  pyroscope:
    image: grafana/pyroscope:1.5.0
    restart: on-failure
    ports:
      - "4040:4040"
