services:
  grafana:
    image: grafana/grafana:10.1.9
    restart: on-failure
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./config/grafana:/etc/grafana-config
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 1s
      start_interval: 0s
      timeout: 10s
      retries: 5

  install-dashboard-dependencies:
    build: images/jb
    restart: on-failure
    depends_on:
      grafana:
        condition: service_healthy
    volumes:
      - ../operations/alloy-mixin:/etc/alloy-mixin
    working_dir: /etc/alloy-mixin
    command: jb install

  # Provision alloy-mixin after Grafana is healthy and running.
  provision-dashboards:
    build: images/grizzly
    restart: on-failure
    depends_on:
      install-dashboard-dependencies:
        condition: service_completed_successfully
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ../operations/alloy-mixin:/etc/alloy-mixin
    working_dir: /etc/alloy-mixin
    command: grr apply grizzly/dashboards.jsonnet

  # Watch dashboards for changes and apply them to Grafana.
  watch-dashboards:
    build: images/grizzly
    restart: on-failure
    depends_on:
      install-dashboard-dependencies:
        condition: service_completed_successfully
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ../operations/alloy-mixin:/etc/alloy-mixin
    working_dir: /etc/alloy-mixin
    command: grr watch dashboards/ grizzly/dashboards.jsonnet


