receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  debug:
# connectors:
# extensions:
service:
  telemetry:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
