[tools]
go = "1.26.2"
node = "24.13.0"
shellcheck = "0.11.0"

[env]
CGO_ENABLED = "{{ env.CGO_ENABLED | default(value='1') }}"

[tasks."build"]
depends = ["build:frontend"]
file = "mise-tasks/_build/build"

[tasks."build:binary"]
file = "mise-tasks/_build/build"

[tasks."build:frontend"]
sources = [
  "internal/web/ui/src/**/*",
  "internal/web/ui/public/**/*",
  "internal/web/ui/index.html",
  "internal/web/ui/package.json",
  "internal/web/ui/package-lock.json",
  "internal/web/ui/vite.config.ts",
  "internal/web/ui/tsconfig*.json",
]
outputs = ["internal/web/ui/dist/**/*"]
file = "mise-tasks/_build/frontend"

[tasks."lint"]
depends = ["lint:scripts"]

[tasks."lint:scripts"]
file = "mise-tasks/_lint/scripts"
