apiVersion: v1
kind: ConfigMap
metadata:
  name: user-pipeline
  namespace: monitoring
data:
  module.alloy: |
    declare "user_pipeline" {
      discovery.relabel "noop" {
        targets = []
      }
    }
