apiVersion: 1

deleteDatasources:
  - name: Mimir

datasources:
- name: Mimir
  type: prometheus
  access: proxy
  orgId: 1
  url: http://mimir:9009/prometheus
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    # The recommended scrape interval is 60s.
    timeInterval: '60s'
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: tid=(\w+)
        name: TraceID
        url: $${__value.raw}
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  uid: tempo
- name: Pyroscope
  type: grafana-pyroscope-datasource
  access: proxy
  orgId: 1
  url: http://pyroscope:4040/
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
