# Test rendering of the chart with the controller explicitly set to StatefulSet and autoscaling with vertical.
controller:
  type: statefulset
  autoscaling:
    vertical:
      enabled: true
      resourcePolicy:
        containerPolicies:
        - containerName: alloy
          controlledResources:
          - cpu
          - memory
          controlledValues: "RequestsAndLimits"
          maxAllowed:
            cpu: "500m"
            memory: "600Mi"
          minAllowed:
            cpu: "250m"
            memory: "100Mi"
  enableStatefulSetAutoDeletePVC: true
