apiVersion: v1
kind: Namespace
metadata:
  name: mimir
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: mimir
data:
  config.yaml: |
    multitenancy_enabled: false
    server:
      http_listen_port: 9009
      log_level: error
    distributor:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
        replication_factor: 1
    blocks_storage:
      backend: filesystem
      bucket_store:
        sync_dir: /tmp/mimir/tsdb-sync
      filesystem:
        dir: /tmp/mimir/data/tsdb
      tsdb:
        dir: /tmp/mimir/tsdb
    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /tmp/mimir/rules
    compactor:
      data_dir: /tmp/mimir/compactor
      sharding_ring:
        kvstore:
          store: memberlist
    store_gateway:
      sharding_ring:
        replication_factor: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.14.2
          args:
            - "-config.file=/etc/mimir/config.yaml"
          ports:
            - containerPort: 9009
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
      volumes:
        - name: config
          configMap:
            name: mimir-config
---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: mimir
spec:
  selector:
    app: mimir
  ports:
    - name: http
      port: 9009
      targetPort: 9009
