events {}

http {
  upstream producers {
    server producer-1:8080;
    server producer-2:8080;
  }

  server {
    listen 8080;
    client_max_body_size 2m;

    location / {
      proxy_pass http://producers;
    }
  }
}
