{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "alloy.fullname" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  # Rules which allow discovery.kubernetes to function.
  {{- if .Values.rbac.allowDiscoveryKubernetes }}
  - apiGroups:
      - ""
      - "discovery.k8s.io"
      - "networking.k8s.io"
    resources:
      - endpoints
      - endpointslices
      - ingresses
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  {{- end }}
  # Rules which allow loki.source.kubernetes and loki.source.podlogs to work.
  {{- if .Values.rbac.allowLokiSource }}
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "monitoring.grafana.com"
    resources:
      - podlogs
    verbs:
      - get
      - list
      - watch
  {{- end }}
  # Rules which allow mimir.rules.kubernetes to work.
  {{- if .Values.rbac.allowMimirRulesKubernetes }}
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  {{- end }}
  # Rules for prometheus.kubernetes.*
  {{- if .Values.rbac.allowPrometheusKubernetes }}
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - podmonitors
      - servicemonitors
      - probes
    verbs:
      - get
      - list
      - watch
  {{- end }}
  # Rules which allow eventhandler to work.
  {{- if .Values.rbac.allowEventHandler }}
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  {{- end }}
  # needed for remote.kubernetes.*
  {{- if .Values.rbac.allowRemoteKubernetes }}
  - apiGroups: [""]
    resources:
      - "configmaps"
      - "secrets"
    verbs:
      - get
      - list
      - watch
  {{- end }}
  # needed for otelcol.processor.k8sattributes
  {{- if .Values.rbac.allowOtelcolProcessorK8sAttributes }}
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alloy.fullname" . }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alloy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "alloy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
