// Code generated by alloy-generate-metadata. DO NOT EDIT.

package metadata

import (
	"github.com/prometheus/client_golang/prometheus"

	"github.com/grafana/alloy/internal/util"
)

type Metrics struct {
	LinesTotal         prometheus.Counter
	ParsingErrorsTotal *prometheus.CounterVec
}

func NewMetrics(r prometheus.Registerer) *Metrics {
	var m Metrics

	m.LinesTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: "loki",
		Subsystem: "source_journal_target",
		Name:      "lines_total",
		Help:      "Total number of successful journal lines read",
	})

	m.ParsingErrorsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: "loki",
		Subsystem: "source_journal_target",
		Name:      "parsing_errors_total",
		Help:      "Total number of parsing errors while reading journal messages",
	}, []string{
		"errors",
	})

	if r != nil {
		m.LinesTotal = util.MustRegisterOrGet(r, m.LinesTotal).(prometheus.Counter)
		m.ParsingErrorsTotal = util.MustRegisterOrGet(r, m.ParsingErrorsTotal).(*prometheus.CounterVec)
	}

	return &m
}
