# Grafana configuration for local development
# Enables passwordless access via anonymous authentication

grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin
  auth:
    disable_login_form: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: mimir
        type: prometheus
        url: http://mimir-nginx.mimir.svc:80/prometheus
        isDefault: true
