name: Blank issue
description: Create a new issue from scratch
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue for Grafana Alloy.

        Please do not use GitHub issues for support questions. If you need help or support, ask a question on [Grafana Community](https://community.grafana.com/c/grafana-alloy) or join the `#alloy` channel on the [Grafana Slack](https://slack.grafana.com/).
  - type: textarea
    attributes:
      label: Add a description
    validations:
      required: true
