name: Community component proposal
description: Propose a new community component.
labels: ["community-component", "proposal", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a community component proposal for Grafana Alloy.

        Make sure you read the [Community Component Guidelines](https://github.com/grafana/alloy/tree/main/docs/developer/adding-community-components.md).
  - type: textarea
    attributes:
      label: Community component name
      description: What is the name of the component you want to add?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Community component maintainer
      description: Are you willing to be the maintainer for this component in Alloy? 
      options:
        - label: I agree to be a maintainer for this component.
  - type: textarea
    attributes:
      label: Community component description
      description: What should this component do?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tip
      description: This is a standard issue postscript to encourage community members to engage with the issue to help gauge its importance.
      options:
        - <sub>React with 👍 if this issue is important to you.</sub>
      default: 0
