name: Feature request
description: Suggest an idea to be added to Grafana Alloy.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a feature request for Grafana Alloy.

        Please do not use GitHub issues for support questions. If you need help or support, ask a question on [Grafana Community](https://community.grafana.com/c/grafana-alloy) or join the `#alloy` channel on the [Grafana Slack](https://slack.grafana.com/).
  - type: textarea
    attributes:
      label: Request
      description: What feature do you want?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Why do you need this feature?
    validations:
      required: true
