name: Proposal
description: Propose a way to solve a problem.
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a proposal for Grafana Alloy.

        Please do not use GitHub issues for support questions. If you need help or support, ask a question on [Grafana Community](https://community.grafana.com/c/grafana-alloy) or join the `#alloy` channel on the [Grafana Slack](https://slack.grafana.com/).
  - type: textarea
    attributes:
      label: Background
      description: What is the background for your proposal? Include your use case here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: How do you propose we implement the functionality?
    validations:
      required: true
