name: publish-technical-documentation-release

on:
  push:
    branches:
      - 'release/*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - 'docs/sources/**'
  workflow_dispatch:
jobs:
  sync:
    if: github.repository == 'grafana/alloy'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: grafana/writers-toolkit/publish-technical-documentation-release@publish-technical-documentation-release/v1
        # ^ This action's version is left as a tag instead of a pinned hash because renovate does
        # not support this type of tag/version format without custom configuration.
        with:
          release_tag_regexp: "^v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
          release_branch_regexp: "^release/v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
          release_branch_with_patch_regexp: "^release/v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
          website_directory: content/docs/alloy
          version_suffix: ""
