name: Test PR
on:
  pull_request:
jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test_linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: go.mod
        cache: false

    - run: make GO_TAGS="nodocker" test
