// Code generated by internal/component/beyla/ebpf/gen/main.go; DO NOT EDIT.
//
//go:build (linux && arm64) || (linux && amd64)

package beyla

import "time"

type RouteHarvestingConfig struct {
	JavaHarvestDelay time.Duration `alloy:"java_harvest_delay,attr,optional"`
}

type Discovery struct {
	BpfPidFilterOff                            bool                  `alloy:"bpf_pid_filter_off,attr,optional"`
	DefaultExcludeInstrument                   Services              `alloy:"default_exclude_instrument,block,optional"`
	DefaultExcludeServices                     Services              `alloy:"default_exclude_services,block,optional"`
	DefaultOtlpGrpcPort                        int                   `alloy:"default_otlp_grpc_port,attr,optional"`
	DisabledRouteHarvesters                    []string              `alloy:"disabled_route_harvesters,attr,optional"`
	ExcludeInstrument                          Services              `alloy:"exclude_instrument,block,optional"`
	ExcludeOTelInstrumentedServices            bool                  `alloy:"exclude_otel_instrumented_services,attr,optional"`
	ExcludeOtelInstrumentedServicesSpanMetrics bool                  `alloy:"exclude_otel_instrumented_services_span_metrics,attr,optional"`
	ExcludeServices                            Services              `alloy:"exclude_services,block,optional"`
	ExcludedLinuxSystemPaths                   []string              `alloy:"excluded_linux_system_paths,attr,optional"`
	Instrument                                 Services              `alloy:"instrument,block,optional"`
	MinProcessAge                              time.Duration         `alloy:"min_process_age,attr,optional"`
	PollInterval                               time.Duration         `alloy:"poll_interval,attr,optional"`
	RouteHarvesterAdvanced                     RouteHarvestingConfig `alloy:"route_harvester_advanced,block,optional"`
	RouteHarvesterTimeout                      time.Duration         `alloy:"route_harvester_timeout,attr,optional"`
	Services                                   Services              `alloy:"services,block,optional"`
	SkipGoSpecificTracers                      bool                  `alloy:"skip_go_specific_tracers,attr,optional"`
	Survey                                     Services              `alloy:"survey,block,optional"`
}

type EBPFBufferSizes struct {
	Http     int `alloy:"http,attr,optional"`
	Kafka    int `alloy:"kafka,attr,optional"`
	Mssql    int `alloy:"mssql,attr,optional"`
	Mysql    int `alloy:"mysql,attr,optional"`
	Postgres int `alloy:"postgres,attr,optional"`
}

type LogEnricherConfig struct {
	AsyncWriterChannelLen int           `alloy:"async_writer_channel_len,attr,optional"`
	AsyncWriterWorkers    int           `alloy:"async_writer_workers,attr,optional"`
	CacheSize             int           `alloy:"cache_size,attr,optional"`
	CacheTtl              time.Duration `alloy:"cache_ttl,attr,optional"`
}

type EBPFMapsConfig struct {
	GlobalScaleFactor int `alloy:"global_scale_factor,attr,optional"`
}

type AWSConfig struct {
	Enabled bool `alloy:"enabled,attr,optional"`
}

type ElasticsearchConfig struct {
	Enabled bool `alloy:"enabled,attr,optional"`
}

type HTTPParsingDefaultAction struct {
}

type HTTPParsingPolicy struct {
	DefaultAction     HTTPParsingDefaultAction `alloy:"default_action,block,optional"`
	ObfuscationString string                   `alloy:"obfuscation_string,attr,optional"`
}

type EnrichmentConfig struct {
	Enabled bool              `alloy:"enabled,attr,optional"`
	Policy  HTTPParsingPolicy `alloy:"policy,block,optional"`
}

type GeminiConfig struct {
	Enabled bool `alloy:"enabled,attr,optional"`
}

type BedrockConfig struct {
	Enabled bool `alloy:"enabled,attr,optional"`
}

type GraphQLConfig struct {
	Enabled bool `alloy:"enabled,attr,optional"`
}

type JSONRPCConfig struct {
	Enabled bool `alloy:"enabled,attr,optional"`
}

type SQLPPConfig struct {
	Enabled          bool     `alloy:"enabled,attr,optional"`
	EndpointPatterns []string `alloy:"endpoint_patterns,attr,optional"`
}

type HTTPPayloadExtraction struct {
	Aws           AWSConfig                  `alloy:"aws,block,optional"`
	Elasticsearch ElasticsearchConfig        `alloy:"elasticsearch,block,optional"`
	Enrichment    EnrichmentConfig           `alloy:"enrichment,block,optional"`
	OpenAI        OpenAIPayloadExtraction    `alloy:"openai,block,optional"`
	Anthropic     AnthropicPayloadExtraction `alloy:"anthropic,block,optional"`
	Gemini        GeminiConfig               `alloy:"gemini,block,optional"`
	Bedrock       BedrockConfig              `alloy:"bedrock,block,optional"`
	Graphql       GraphQLConfig              `alloy:"graphql,block,optional"`
	Jsonrpc       JSONRPCConfig              `alloy:"jsonrpc,block,optional"`
	Sqlpp         SQLPPConfig                `alloy:"sqlpp,block,optional"`
}

type PayloadExtraction struct {
	HTTP HTTPPayloadExtraction `alloy:"http,block,optional"`
}

type RedisDBCacheConfig struct {
	Enabled bool `alloy:"enabled,attr,optional"`
	MaxSize int  `alloy:"max_size,attr,optional"`
}

type EBPF struct {
	BatchLength                         int                `alloy:"batch_length,attr,optional"`
	BatchTimeout                        time.Duration      `alloy:"batch_timeout,attr,optional"`
	BpfDebug                            bool               `alloy:"bpf_debug,attr,optional"`
	BpfFsPath                           string             `alloy:"bpf_fs_path,attr,optional"`
	BufferSizes                         EBPFBufferSizes    `alloy:"buffer_sizes,block,optional"`
	ContextPropagation                  string             `alloy:"context_propagation,attr,optional"`
	CouchbaseDbCacheSize                int                `alloy:"couchbase_db_cache_size,attr,optional"`
	DisableBlackBoxCp                   bool               `alloy:"disable_black_box_cp,attr,optional"`
	DnsRequestTimeout                   time.Duration      `alloy:"dns_request_timeout,attr,optional"`
	ForceBpfMapReader                   string             `alloy:"force_bpf_map_reader,attr,optional"`
	HeuristicSQLDetect                  bool               `alloy:"heuristic_sql_detect,attr,optional"`
	HighRequestVolume                   bool               `alloy:"high_request_volume,attr,optional"`
	HTTPRequestTimeout                  time.Duration      `alloy:"http_request_timeout,attr,optional"`
	InstrumentCuda                      int                `alloy:"instrument_cuda,attr,optional"`
	KafkaTopicUuidCacheSize             int                `alloy:"kafka_topic_uuid_cache_size,attr,optional"`
	LogEnricher                         LogEnricherConfig  `alloy:"log_enricher,block,optional"`
	MapsConfig                          EBPFMapsConfig     `alloy:"maps_config,block,optional"`
	MaxTransactionTime                  time.Duration      `alloy:"max_transaction_time,attr,optional"`
	MongoRequestsCacheSize              int                `alloy:"mongo_requests_cache_size,attr,optional"`
	MssqlPreparedStatementsCacheSize    int                `alloy:"mssql_prepared_statements_cache_size,attr,optional"`
	MysqlPreparedStatementsCacheSize    int                `alloy:"mysql_prepared_statements_cache_size,attr,optional"`
	OverrideBpfloopEnabled              bool               `alloy:"override_bpfloop_enabled,attr,optional"`
	PayloadExtraction                   PayloadExtraction  `alloy:"payload_extraction,block,optional"`
	PostgresPreparedStatementsCacheSize int                `alloy:"postgres_prepared_statements_cache_size,attr,optional"`
	ProtocolDebug                       bool               `alloy:"protocol_debug_print,attr,optional"`
	RedisDbCache                        RedisDBCacheConfig `alloy:"redis_db_cache,block,optional"`
	TrackRequestHeaders                 bool               `alloy:"track_request_headers,attr,optional"`
	TrafficControlBackend               string             `alloy:"traffic_control_backend,attr,optional"`
	WakeupLen                           int                `alloy:"wakeup_len,attr,optional"`
}

type InjectorSDKExport struct {
	Logs    *bool `alloy:"logs,attr,optional"`
	Metrics *bool `alloy:"metrics,attr,optional"`
	Traces  *bool `alloy:"traces,attr,optional"`
}

type InjectorSDKResource struct {
	AddK8sIPAttribute              bool              `alloy:"addK8sIPAttribute,attr,optional"`
	AddK8sUIDAttributes            *bool             `alloy:"add_k8s_attributes,attr,optional"`
	Attributes                     map[string]string `alloy:"attributes,attr,optional"`
	UseLabelsForResourceAttributes *bool             `alloy:"use_labels,attr,optional"`
}

type SamplerConfig struct {
	Arg  string `alloy:"arg,attr,optional"`
	Name string `alloy:"name,attr,optional"`
}

type InjectorWebhook struct {
	CertPath string         `alloy:"cert_path,attr,optional"`
	Enable   bool           `alloy:"enable,attr,optional"`
	KeyPath  string         `alloy:"key_path,attr,optional"`
	Port     *int           `alloy:"port,attr,optional"`
	Timeout  *time.Duration `alloy:"timeout,attr,optional"`
}

type Injector struct {
	Debug             *bool               `alloy:"debug,attr,optional"`
	NoAutoRestart     *bool               `alloy:"disable_auto_restart,attr,optional"`
	EnabledSDKs       []string            `alloy:"enabled_sdks,attr,optional"`
	Export            InjectorSDKExport   `alloy:"export,block,optional"`
	HostMountPath     string              `alloy:"host_mount_path,attr,optional"`
	HostPathVolumeDir string              `alloy:"host_path_volume,attr,optional"`
	ImageVolumePath   string              `alloy:"image_volume_path,attr,optional"`
	Instrument        Services            `alloy:"instrument,block,optional"`
	ManageSDKVersions *bool               `alloy:"manage_sdk_versions,attr,optional"`
	Propagators       []string            `alloy:"propagators,attr,optional"`
	Resources         InjectorSDKResource `alloy:"resources,block,optional"`
	DefaultSampler    SamplerConfig       `alloy:"sampler,block,optional"`
	SDKPkgVersion     string              `alloy:"sdk_package_version,attr,optional"`
	Webhook           InjectorWebhook     `alloy:"webhook,block,optional"`
	OTELEndpoint      string              `alloy:"otel_endpoint,attr,optional"`
}

type InternalMetrics struct {
	BpfMetricScrapeInterval time.Duration `alloy:"bpf_metric_scrape_interval,attr,optional"`
	Exporter                string        `alloy:"exporter,attr,optional"`
}

type Routes struct {
	IgnoredEvents             string   `alloy:"ignore_mode,attr,optional"`
	IgnorePatterns            []string `alloy:"ignored_patterns,attr,optional"`
	MaxPathSegmentCardinality int      `alloy:"max_path_segment_cardinality,attr,optional"`
	Patterns                  []string `alloy:"patterns,attr,optional"`
	Unmatch                   string   `alloy:"unmatched,attr,optional"`
	WildcardChar              string   `alloy:"wildcard_char,attr,optional"`
}

type IPInfoConfig struct {
	Path string `alloy:"path,attr,optional"`
}

type MaxMindConfig struct {
	AsnPath     string `alloy:"asn_path,attr,optional"`
	CountryPath string `alloy:"country_path,attr,optional"`
}

type GeoIP struct {
	CacheExpiry time.Duration `alloy:"cache_expiry,attr,optional"`
	CacheLen    int           `alloy:"cache_len,attr,optional"`
	Ipinfo      IPInfoConfig  `alloy:"ipinfo,block,optional"`
	Maxmind     MaxMindConfig `alloy:"maxmind,block,optional"`
}

type ReverseDNS struct {
	CacheExpiry time.Duration `alloy:"cache_expiry,attr,optional"`
	CacheLen    int           `alloy:"cache_len,attr,optional"`
	Type        string        `alloy:"type,attr,optional"`
}

type Stats struct {
	AgentIP      string     `alloy:"agent_ip,attr,optional"`
	AgentIPIface string     `alloy:"agent_ip_iface,attr,optional"`
	AgentIPType  string     `alloy:"agent_ip_type,attr,optional"`
	CIDRs        []string   `alloy:"cidrs,attr,optional"`
	GeoIp        GeoIP      `alloy:"geo_ip,block,optional"`
	Print        bool       `alloy:"print_stats,attr,optional"`
	ReverseDns   ReverseDNS `alloy:"reverse_dns,block,optional"`
}
