// Code generated by internal/component/beyla/ebpf/gen/main.go; DO NOT EDIT.
//
//go:build (linux && arm64) || (linux && amd64)

package beyla

// addDiscoveryConfig adds discovery configuration.
func (c *Component) addDiscoveryConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if c.args.Discovery.BpfPidFilterOff {
		m["bpf_pid_filter_off"] = true
	}
	if len(c.args.Discovery.DefaultExcludeInstrument) > 0 {
		m["default_exclude_instrument"] = buildServicesYAML(c.args.Discovery.DefaultExcludeInstrument)
	}
	if len(c.args.Discovery.DefaultExcludeServices) > 0 {
		m["default_exclude_services"] = buildServicesYAML(c.args.Discovery.DefaultExcludeServices)
	}
	if v := c.args.Discovery.DefaultOtlpGrpcPort; v != 0 {
		m["default_otlp_grpc_port"] = v
	}
	if v := c.args.Discovery.DisabledRouteHarvesters; len(v) > 0 {
		m["disabled_route_harvesters"] = v
	}
	if len(c.args.Discovery.ExcludeInstrument) > 0 {
		m["exclude_instrument"] = buildServicesYAML(c.args.Discovery.ExcludeInstrument)
	}
	if c.args.Discovery.ExcludeOTelInstrumentedServices {
		m["exclude_otel_instrumented_services"] = true
	}
	if c.args.Discovery.ExcludeOtelInstrumentedServicesSpanMetrics {
		m["exclude_otel_instrumented_services_span_metrics"] = true
	}
	if len(c.args.Discovery.ExcludeServices) > 0 {
		m["exclude_services"] = buildServicesYAML(c.args.Discovery.ExcludeServices)
	}
	if v := c.args.Discovery.ExcludedLinuxSystemPaths; len(v) > 0 {
		m["excluded_linux_system_paths"] = v
	}
	if len(c.args.Discovery.Instrument) > 0 {
		m["instrument"] = buildServicesYAML(c.args.Discovery.Instrument)
	}
	if v := c.args.Discovery.MinProcessAge; v != 0 {
		m["min_process_age"] = v.String()
	}
	if v := c.args.Discovery.PollInterval; v != 0 {
		m["poll_interval"] = v.String()
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.Discovery.RouteHarvesterAdvanced.JavaHarvestDelay; v != 0 {
			m1["java_harvest_delay"] = v.String()
		}
		if len(m1) > 0 {
			m["route_harvester_advanced"] = m1
		}
	}
	if v := c.args.Discovery.RouteHarvesterTimeout; v != 0 {
		m["route_harvester_timeout"] = v.String()
	}
	if len(c.args.Discovery.Services) > 0 {
		m["services"] = buildServicesYAML(c.args.Discovery.Services)
	}
	if c.args.Discovery.SkipGoSpecificTracers {
		m["skip_go_specific_tracers"] = true
	}
	if len(c.args.Discovery.Survey) > 0 {
		m["survey"] = buildServicesYAML(c.args.Discovery.Survey)
	}
	if len(m) > 0 {
		config["discovery"] = m
	}
}

// addEbpfConfig adds ebpf configuration.
func (c *Component) addEbpfConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := c.args.EBPF.BatchLength; v != 0 {
		m["batch_length"] = v
	}
	if v := c.args.EBPF.BatchTimeout; v != 0 {
		m["batch_timeout"] = v.String()
	}
	if c.args.EBPF.BpfDebug {
		m["bpf_debug"] = true
	}
	if v := c.args.EBPF.BpfFsPath; v != "" {
		m["bpf_fs_path"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.EBPF.BufferSizes.Http; v != 0 {
			m1["http"] = v
		}
		if v := c.args.EBPF.BufferSizes.Kafka; v != 0 {
			m1["kafka"] = v
		}
		if v := c.args.EBPF.BufferSizes.Mssql; v != 0 {
			m1["mssql"] = v
		}
		if v := c.args.EBPF.BufferSizes.Mysql; v != 0 {
			m1["mysql"] = v
		}
		if v := c.args.EBPF.BufferSizes.Postgres; v != 0 {
			m1["postgres"] = v
		}
		if len(m1) > 0 {
			m["buffer_sizes"] = m1
		}
	}
	if v := c.args.EBPF.ContextPropagation; v != "" {
		m["context_propagation"] = v
	}
	if v := c.args.EBPF.CouchbaseDbCacheSize; v != 0 {
		m["couchbase_db_cache_size"] = v
	}
	if c.args.EBPF.DisableBlackBoxCp {
		m["disable_black_box_cp"] = true
	}
	if v := c.args.EBPF.DnsRequestTimeout; v != 0 {
		m["dns_request_timeout"] = v.String()
	}
	if v := c.args.EBPF.ForceBpfMapReader; v != "" {
		m["force_bpf_map_reader"] = v
	}
	if c.args.EBPF.HeuristicSQLDetect {
		m["heuristic_sql_detect"] = true
	}
	if c.args.EBPF.HighRequestVolume {
		m["high_request_volume"] = true
	}
	if v := c.args.EBPF.HTTPRequestTimeout; v != 0 {
		m["http_request_timeout"] = v.String()
	}
	if v := c.args.EBPF.InstrumentCuda; v != 0 {
		m["instrument_cuda"] = v
	}
	if v := c.args.EBPF.KafkaTopicUuidCacheSize; v != 0 {
		m["kafka_topic_uuid_cache_size"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.EBPF.LogEnricher.AsyncWriterChannelLen; v != 0 {
			m1["async_writer_channel_len"] = v
		}
		if v := c.args.EBPF.LogEnricher.AsyncWriterWorkers; v != 0 {
			m1["async_writer_workers"] = v
		}
		if v := c.args.EBPF.LogEnricher.CacheSize; v != 0 {
			m1["cache_size"] = v
		}
		if v := c.args.EBPF.LogEnricher.CacheTtl; v != 0 {
			m1["cache_ttl"] = v.String()
		}
		// TODO: schema field "services" has no Alloy mapping
		if len(m1) > 0 {
			m["log_enricher"] = m1
		}
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.EBPF.MapsConfig.GlobalScaleFactor; v != 0 {
			m1["global_scale_factor"] = v
		}
		if len(m1) > 0 {
			m["maps_config"] = m1
		}
	}
	if v := c.args.EBPF.MaxTransactionTime; v != 0 {
		m["max_transaction_time"] = v.String()
	}
	if v := c.args.EBPF.MongoRequestsCacheSize; v != 0 {
		m["mongo_requests_cache_size"] = v
	}
	if v := c.args.EBPF.MssqlPreparedStatementsCacheSize; v != 0 {
		m["mssql_prepared_statements_cache_size"] = v
	}
	if v := c.args.EBPF.MysqlPreparedStatementsCacheSize; v != 0 {
		m["mysql_prepared_statements_cache_size"] = v
	}
	if c.args.EBPF.OverrideBpfloopEnabled {
		m["override_bpfloop_enabled"] = true
	}
	{
		m1 := make(map[string]interface{})
		{
			m2 := make(map[string]interface{})
			{
				m3 := make(map[string]interface{})
				if c.args.EBPF.PayloadExtraction.HTTP.Aws.Enabled {
					m3["enabled"] = true
				}
				if len(m3) > 0 {
					m2["aws"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if c.args.EBPF.PayloadExtraction.HTTP.Elasticsearch.Enabled {
					m3["enabled"] = true
				}
				if len(m3) > 0 {
					m2["elasticsearch"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if c.args.EBPF.PayloadExtraction.HTTP.Enrichment.Enabled {
					m3["enabled"] = true
				}
				{
					m4 := make(map[string]interface{})
					{
						m5 := make(map[string]interface{})
						// TODO: schema field "body" has no Alloy mapping
						// TODO: schema field "headers" has no Alloy mapping
						if len(m5) > 0 {
							m4["default_action"] = m5
						}
					}
					if v := c.args.EBPF.PayloadExtraction.HTTP.Enrichment.Policy.ObfuscationString; v != "" {
						m4["obfuscation_string"] = v
					}
					if len(m4) > 0 {
						m3["policy"] = m4
					}
				}
				// TODO: schema field "rules" has no Alloy mapping
				if len(m3) > 0 {
					m2["enrichment"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				{
					m4 := make(map[string]interface{})
					if c.args.EBPF.PayloadExtraction.HTTP.OpenAI.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["openai"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if c.args.EBPF.PayloadExtraction.HTTP.Anthropic.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["anthropic"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if c.args.EBPF.PayloadExtraction.HTTP.Gemini.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["gemini"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if c.args.EBPF.PayloadExtraction.HTTP.Bedrock.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["bedrock"] = m4
					}
				}
				if len(m3) > 0 {
					m2["genai"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if c.args.EBPF.PayloadExtraction.HTTP.Graphql.Enabled {
					m3["enabled"] = true
				}
				if len(m3) > 0 {
					m2["graphql"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if c.args.EBPF.PayloadExtraction.HTTP.Jsonrpc.Enabled {
					m3["enabled"] = true
				}
				if len(m3) > 0 {
					m2["jsonrpc"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if c.args.EBPF.PayloadExtraction.HTTP.Sqlpp.Enabled {
					m3["enabled"] = true
				}
				if v := c.args.EBPF.PayloadExtraction.HTTP.Sqlpp.EndpointPatterns; len(v) > 0 {
					m3["endpoint_patterns"] = v
				}
				if len(m3) > 0 {
					m2["sqlpp"] = m3
				}
			}
			if len(m2) > 0 {
				m1["http"] = m2
			}
		}
		if len(m1) > 0 {
			m["payload_extraction"] = m1
		}
	}
	if v := c.args.EBPF.PostgresPreparedStatementsCacheSize; v != 0 {
		m["postgres_prepared_statements_cache_size"] = v
	}
	if c.args.EBPF.ProtocolDebug {
		m["protocol_debug_print"] = true
	}
	{
		m1 := make(map[string]interface{})
		if c.args.EBPF.RedisDbCache.Enabled {
			m1["enabled"] = true
		}
		if v := c.args.EBPF.RedisDbCache.MaxSize; v != 0 {
			m1["max_size"] = v
		}
		if len(m1) > 0 {
			m["redis_db_cache"] = m1
		}
	}
	if c.args.EBPF.TrackRequestHeaders {
		m["track_request_headers"] = true
	}
	if v := c.args.EBPF.TrafficControlBackend; v != "" {
		m["traffic_control_backend"] = v
	}
	if v := c.args.EBPF.WakeupLen; v != 0 {
		m["wakeup_len"] = v
	}
	if len(m) > 0 {
		config["ebpf"] = m
	}
}

// addInjectorConfig adds injector configuration.
func (c *Component) addInjectorConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := c.args.Injector.Debug; v != nil {
		m["debug"] = *v
	}
	if v := c.args.Injector.NoAutoRestart; v != nil {
		m["disable_auto_restart"] = *v
	}
	if v := c.args.Injector.EnabledSDKs; len(v) > 0 {
		m["enabled_sdks"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.Injector.Export.Logs; v != nil {
			m1["logs"] = *v
		}
		if v := c.args.Injector.Export.Metrics; v != nil {
			m1["metrics"] = *v
		}
		if v := c.args.Injector.Export.Traces; v != nil {
			m1["traces"] = *v
		}
		if len(m1) > 0 {
			m["export"] = m1
		}
	}
	if v := c.args.Injector.HostMountPath; v != "" {
		m["host_mount_path"] = v
	}
	if v := c.args.Injector.HostPathVolumeDir; v != "" {
		m["host_path_volume"] = v
	}
	if v := c.args.Injector.ImageVolumePath; v != "" {
		m["image_volume_path"] = v
	}
	if len(c.args.Injector.Instrument) > 0 {
		m["instrument"] = buildServicesYAML(c.args.Injector.Instrument)
	}
	if v := c.args.Injector.ManageSDKVersions; v != nil {
		m["manage_sdk_versions"] = *v
	}
	if v := c.args.Injector.Propagators; len(v) > 0 {
		m["propagators"] = v
	}
	{
		m1 := make(map[string]interface{})
		if c.args.Injector.Resources.AddK8sIPAttribute {
			m1["addK8sIPAttribute"] = true
		}
		if v := c.args.Injector.Resources.AddK8sUIDAttributes; v != nil {
			m1["add_k8s_attributes"] = *v
		}
		if v := c.args.Injector.Resources.Attributes; len(v) > 0 {
			m1["attributes"] = v
		}
		if v := c.args.Injector.Resources.UseLabelsForResourceAttributes; v != nil {
			m1["use_labels"] = *v
		}
		if len(m1) > 0 {
			m["resources"] = m1
		}
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.Injector.DefaultSampler.Arg; v != "" {
			m1["arg"] = v
		}
		if v := c.args.Injector.DefaultSampler.Name; v != "" {
			m1["name"] = v
		}
		if len(m1) > 0 {
			m["sampler"] = m1
		}
	}
	if v := c.args.Injector.SDKPkgVersion; v != "" {
		m["sdk_package_version"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.Injector.Webhook.CertPath; v != "" {
			m1["cert_path"] = v
		}
		if c.args.Injector.Webhook.Enable {
			m1["enable"] = true
		}
		if v := c.args.Injector.Webhook.KeyPath; v != "" {
			m1["key_path"] = v
		}
		if v := c.args.Injector.Webhook.Port; v != nil {
			m1["port"] = *v
		}
		if v := c.args.Injector.Webhook.Timeout; v != nil {
			m1["timeout"] = v.String()
		}
		if len(m1) > 0 {
			m["webhook"] = m1
		}
	}
	if v := c.args.Injector.OTELEndpoint; v != "" {
		m["otel_endpoint"] = v
	}
	if len(m) > 0 {
		config["injector"] = m
	}
}

// addInternalMetricsConfig adds internal_metrics configuration.
func (c *Component) addInternalMetricsConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := c.args.InternalMetrics.BpfMetricScrapeInterval; v != 0 {
		m["bpf_metric_scrape_interval"] = v.String()
	}
	if v := c.args.InternalMetrics.Exporter; v != "" {
		m["exporter"] = v
	}
	if len(m) > 0 {
		config["internal_metrics"] = m
	}
}

// addRoutesConfig adds routes configuration.
func (c *Component) addRoutesConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := c.args.Routes.IgnoredEvents; v != "" {
		m["ignore_mode"] = v
	}
	if v := c.args.Routes.IgnorePatterns; len(v) > 0 {
		m["ignored_patterns"] = v
	}
	if v := c.args.Routes.MaxPathSegmentCardinality; v != 0 {
		m["max_path_segment_cardinality"] = v
	}
	if v := c.args.Routes.Patterns; len(v) > 0 {
		m["patterns"] = v
	}
	if v := c.args.Routes.Unmatch; v != "" {
		m["unmatched"] = v
	}
	if v := c.args.Routes.WildcardChar; v != "" {
		m["wildcard_char"] = v
	}
	if len(m) > 0 {
		config["routes"] = m
	}
}

// addStatsConfig adds stats configuration.
func (c *Component) addStatsConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := c.args.Stats.AgentIP; v != "" {
		m["agent_ip"] = v
	}
	if v := c.args.Stats.AgentIPIface; v != "" {
		m["agent_ip_iface"] = v
	}
	if v := c.args.Stats.AgentIPType; v != "" {
		m["agent_ip_type"] = v
	}
	if v := c.args.Stats.CIDRs; len(v) > 0 {
		m["cidrs"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.Stats.GeoIp.CacheExpiry; v != 0 {
			m1["cache_expiry"] = v.String()
		}
		if v := c.args.Stats.GeoIp.CacheLen; v != 0 {
			m1["cache_len"] = v
		}
		{
			m2 := make(map[string]interface{})
			if v := c.args.Stats.GeoIp.Ipinfo.Path; v != "" {
				m2["path"] = v
			}
			if len(m2) > 0 {
				m1["ipinfo"] = m2
			}
		}
		{
			m2 := make(map[string]interface{})
			if v := c.args.Stats.GeoIp.Maxmind.AsnPath; v != "" {
				m2["asn_path"] = v
			}
			if v := c.args.Stats.GeoIp.Maxmind.CountryPath; v != "" {
				m2["country_path"] = v
			}
			if len(m2) > 0 {
				m1["maxmind"] = m2
			}
		}
		if len(m1) > 0 {
			m["geo_ip"] = m1
		}
	}
	if c.args.Stats.Print {
		m["print_stats"] = true
	}
	{
		m1 := make(map[string]interface{})
		if v := c.args.Stats.ReverseDns.CacheExpiry; v != 0 {
			m1["cache_expiry"] = v.String()
		}
		if v := c.args.Stats.ReverseDns.CacheLen; v != 0 {
			m1["cache_len"] = v
		}
		if v := c.args.Stats.ReverseDns.Type; v != "" {
			m1["type"] = v
		}
		if len(m1) > 0 {
			m["reverse_dns"] = m1
		}
	}
	if len(m) > 0 {
		config["stats"] = m
	}
}

// fillPrometheusExportConfig fills m with prometheus_export fields from metrics.
func (c *Component) fillPrometheusExportConfig(m map[string]interface{}) {
	if v := c.args.Metrics.Features; len(v) > 0 {
		m["features"] = v
	}
	if v := c.args.Metrics.Instrumentations; len(v) > 0 {
		m["instrumentations"] = v
	}
	if c.args.Metrics.AllowServiceGraphSelfReferences {
		m["allow_service_graph_self_references"] = true
	}
	if v := c.args.Metrics.ExtraResourceLabels; len(v) > 0 {
		m["extra_resource_attributes"] = v
	}
	if v := c.args.Metrics.ExtraSpanResourceLabels; len(v) > 0 {
		m["extra_span_resource_attributes"] = v
	}
	if c.args.Metrics.NativeHistograms {
		m["native_histograms"] = true
	}
	if v := c.args.Metrics.ExemplarFilter; v != "" {
		m["exemplar_filter"] = v
	}
}

// fillNetworkConfig fills m with network fields from metrics.network.
func (c *Component) fillNetworkConfig(m map[string]interface{}) {
	if v := c.args.Metrics.Network.AgentIP; v != "" {
		m["agent_ip"] = v
	}
	if v := c.args.Metrics.Network.AgentIPIface; v != "" {
		m["agent_ip_iface"] = v
	}
	if v := c.args.Metrics.Network.AgentIPType; v != "" {
		m["agent_ip_type"] = v
	}
	if v := c.args.Metrics.Network.CacheActiveTimeout; v != 0 {
		m["cache_active_timeout"] = v.String()
	}
	if v := c.args.Metrics.Network.CacheMaxFlows; v != 0 {
		m["cache_max_flows"] = v
	}
	if v := c.args.Metrics.Network.CIDRs; len(v) > 0 {
		m["cidrs"] = v
	}
	if v := c.args.Metrics.Network.Direction; v != "" {
		m["direction"] = v
	}
	if c.args.Metrics.Network.Enable {
		m["enable"] = true
	}
	if v := c.args.Metrics.Network.ExcludeInterfaces; len(v) > 0 {
		m["exclude_interfaces"] = v
	}
	if v := c.args.Metrics.Network.ExcludeProtocols; len(v) > 0 {
		m["exclude_protocols"] = v
	}
	if v := c.args.Metrics.Network.Interfaces; len(v) > 0 {
		m["interfaces"] = v
	}
	if v := c.args.Metrics.Network.Protocols; len(v) > 0 {
		m["protocols"] = v
	}
	if v := c.args.Metrics.Network.Sampling; v != 0 {
		m["sampling"] = v
	}
	if v := c.args.Metrics.Network.Source; v != "" {
		m["source"] = v
	}
}

// fillAttributeFamiliesConfig builds a YAML map keyed by the "attr" field.
func fillAttributeFamiliesConfig(m map[string]interface{}, items AttributeFamilies) {
	for _, item := range items {
		sub := make(map[string]interface{})
		if v := item.Match; v != "" {
			sub["match"] = v
		}
		if v := item.NotMatch; v != "" {
			sub["not_match"] = v
		}
		if len(sub) > 0 {
			m[item.Attr] = sub
		}
	}
}

// fillSelectionsConfig builds a YAML map keyed by the "attr" field.
func fillSelectionsConfig(m map[string]interface{}, items Selections) {
	for _, item := range items {
		sub := make(map[string]interface{})
		if v := item.Exclude; len(v) > 0 {
			sub["exclude"] = v
		}
		if v := item.Include; len(v) > 0 {
			sub["include"] = v
		}
		if len(sub) > 0 {
			m[item.Section] = sub
		}
	}
}

func buildServicesYAML(items Services) []map[string]interface{} {
	result := make([]map[string]interface{}, 0, len(items))
	for _, item := range items {
		m := make(map[string]interface{})
		if v := item.CmdArgs; v != "" {
			m["cmd_args"] = v
		}
		if item.ContainersOnly {
			m["containers_only"] = true
		}
		if v := item.Path; v != "" {
			m["exe_path"] = v
		}
		if v := item.ExportModes; len(v) > 0 {
			m["exports"] = v
		}
		if v := item.Kubernetes.DaemonSetName; v != "" {
			m["k8s_daemonset_name"] = v
		}
		if v := item.Kubernetes.DeploymentName; v != "" {
			m["k8s_deployment_name"] = v
		}
		if v := item.Kubernetes.Namespace; v != "" {
			m["k8s_namespace"] = v
		}
		if v := item.Kubernetes.OwnerName; v != "" {
			m["k8s_owner_name"] = v
		}
		if v := item.Kubernetes.PodAnnotations; len(v) > 0 {
			m["k8s_pod_annotations"] = v
		}
		if v := item.Kubernetes.PodLabels; len(v) > 0 {
			m["k8s_pod_labels"] = v
		}
		if v := item.Kubernetes.PodName; v != "" {
			m["k8s_pod_name"] = v
		}
		if v := item.Kubernetes.ReplicaSetName; v != "" {
			m["k8s_replicaset_name"] = v
		}
		if v := item.Kubernetes.StatefulSetName; v != "" {
			m["k8s_statefulset_name"] = v
		}
		if v := item.Name; v != "" {
			m["name"] = v
		}
		if v := item.Namespace; v != "" {
			m["namespace"] = v
		}
		if v := item.OpenPorts; v != "" {
			m["open_ports"] = v
		}
		{
			m1 := make(map[string]interface{})
			if v := item.Sampler.Arg; v != "" {
				m1["arg"] = v
			}
			if v := item.Sampler.Name; v != "" {
				m1["name"] = v
			}
			if len(m1) > 0 {
				m["sampler"] = m1
			}
		}
		if len(m) > 0 {
			result = append(result, m)
		}
	}
	return result
}
