//go:build alloy_custom_components && alloy_component_beyla_ebpf

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/beyla/ebpf" // Import beyla.ebpf
