//go:build alloy_custom_components && alloy_component_prometheus_receive_http

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/prometheus/receive_http" // Import prometheus.receive_http
