//go:build alloy_custom_components && alloy_component_prometheus_exporter_mysql

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/prometheus/exporter/mysql" // Import prometheus.exporter.mysql
