//go:build alloy_custom_components && alloy_component_prometheus_operator_scrapeconfigs

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/prometheus/operator/scrapeconfigs" // Import prometheus.operator.scrapeconfigs
