//go:build alloy_custom_components && alloy_component_otelcol_receiver_syslog

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/receiver/syslog" // Import otelcol.receiver.syslog
