//go:build alloy_custom_components && alloy_component_prometheus_echo

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/prometheus/echo" // Import prometheus.echo
