//go:build alloy_custom_components && alloy_component_discovery_kuma

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/discovery/kuma" // Import discovery.kuma
