//go:build alloy_custom_components && alloy_component_otelcol_auth_sigv4

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/auth/sigv4" // Import otelcol.auth.sigv4
