//go:build alloy_custom_components && alloy_component_otelcol_connector_count

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/connector/count" // Import otelcol.connector.count
