//go:build alloy_custom_components && alloy_component_database_observability_sql_server

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/database_observability/sql_server" // Import database_observability.sql_server
