//go:build alloy_custom_components && alloy_component_loki_source_azure_event_hubs

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/loki/source/azure_event_hubs" // Import loki.source.azure_event_hubs
