//go:build alloy_custom_components && alloy_component_discovery_dns

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/discovery/dns" // Import discovery.dns
