//go:build alloy_custom_components && alloy_component_prometheus_enrich

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/prometheus/enrich" // Import prometheus.enrich
