//go:build alloy_custom_components && alloy_component_otelcol_auth_bearer

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/auth/bearer" // Import otelcol.auth.bearer
