//go:build alloy_custom_components && alloy_component_remote_vault

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/remote/vault" // Import remote.vault
