//go:build alloy_custom_components && alloy_component_mimir_rules_kubernetes

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/mimir/rules/kubernetes" // Import mimir.rules.kubernetes
