//go:build alloy_custom_components && alloy_component_loki_source_heroku

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/loki/source/heroku" // Import loki.source.heroku
