//go:build alloy_custom_components && (alloy_component_discovery_aws || alloy_component_discovery_ec2 || alloy_component_discovery_lightsail)

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/discovery/aws" // Import discovery.aws, discovery.ec2, and discovery.lightsail
