//go:build alloy_custom_components && alloy_component_otelcol_exporter_faro

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/exporter/faro" // Import otelcol.exporter.faro
