//go:build alloy_custom_components && alloy_component_database_observability_postgres

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/database_observability/postgres" // Import database_observability.postgres
