//go:build alloy_custom_components && alloy_component_otelcol_auth_oauth2

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/auth/oauth2" // Import otelcol.auth.oauth2
