//go:build alloy_custom_components && alloy_component_otelcol_processor_span

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/processor/span" // Import otelcol.processor.span
