//go:build alloy_custom_components && alloy_component_pyroscope_receive_http

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/pyroscope/receive_http" // Import pyroscope.receive_http
