//go:build alloy_custom_components && alloy_component_prometheus_exporter_static

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/prometheus/exporter/static" // Import prometheus.exporter.static
