//go:build alloy_custom_components && alloy_component_pyroscope_ebpf

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/pyroscope/ebpf" // Import pyroscope.ebpf
