//go:build alloy_custom_components && alloy_component_otelcol_processor_interval

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/processor/interval" // Import otelcol.processor.interval
