//go:build alloy_custom_components && alloy_component_faro_receiver

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/faro/receiver" // Import faro.receiver
