//go:build alloy_custom_components && alloy_component_discovery_marathon

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/discovery/marathon" // Import discovery.marathon
