//go:build alloy_custom_components && alloy_component_otelcol_processor_batch

// Code generated by internal/component/all/generate. DO NOT EDIT.

package all

import _ "github.com/grafana/alloy/internal/component/otelcol/processor/batch" // Import otelcol.processor.batch
