package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateServicesDoc(t *testing.T) {
	doc := generateServicesDoc()
	for _, expected := range []string{
		"This file is automatically generated",
		"{{< column-list >}}",
		"* Namespace: `AWS/EC2`",
		"{{< /column-list >}}",
	} {
		if !strings.Contains(doc, expected) {
			t.Fatalf("generateServicesDoc() does not contain %q", expected)
		}
	}
	if strings.Contains(doc, servicesListReplacement) {
		t.Fatalf("generateServicesDoc() contains unreplaced placeholder %q", servicesListReplacement)
	}
}

func TestSyncServicesDoc(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cloudwatch.md")
	expected := "generated documentation\n"
	changed, err := syncServicesDoc(path, expected)
	if err != nil {
		t.Fatalf("syncServicesDoc() returned an error: %v", err)
	}
	if !changed {
		t.Fatal("syncServicesDoc() changed = false, want true")
	}

	updated, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read synced file: %v", err)
	}
	if string(updated) != expected {
		t.Fatalf("synced file = %q, want %q", updated, expected)
	}

	changed, err = syncServicesDoc(path, expected)
	if err != nil {
		t.Fatalf("second syncServicesDoc() returned an error: %v", err)
	}
	if changed {
		t.Fatal("second syncServicesDoc() changed = true, want false")
	}
}

func TestSyncServicesDocPreservesPermissions(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cloudwatch.md")
	if err := os.WriteFile(path, []byte("old\n"), 0o640); err != nil {
		t.Fatalf("write test file: %v", err)
	}

	if _, err := syncServicesDoc(path, "new\n"); err != nil {
		t.Fatalf("syncServicesDoc() returned an error: %v", err)
	}
	fileInfo, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat synced file: %v", err)
	}
	if got, want := fileInfo.Mode().Perm(), os.FileMode(0o640); got != want {
		t.Fatalf("synced file permissions = %v, want %v", got, want)
	}
}
