// Code generated by internal/component/beyla/ebpf/internal/config/gen/main.go; DO NOT EDIT.

package config

// addDiscoveryConfig adds discovery configuration.
func (b *builder) addDiscoveryConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if b.args.Discovery.BpfPidFilterOff {
		m["bpf_pid_filter_off"] = true
	}
	if len(b.args.Discovery.DefaultExcludeInstrument) > 0 {
		m["default_exclude_instrument"] = buildServicesYAML(b.args.Discovery.DefaultExcludeInstrument)
	}
	if len(b.args.Discovery.DefaultExcludeServices) > 0 {
		m["default_exclude_services"] = buildServicesYAML(b.args.Discovery.DefaultExcludeServices)
	}
	if v := b.args.Discovery.DefaultOtlpGrpcPort; v != 0 {
		m["default_otlp_grpc_port"] = v
	}
	if v := b.args.Discovery.DisabledRouteHarvesters; len(v) > 0 {
		m["disabled_route_harvesters"] = v
	}
	if len(b.args.Discovery.ExcludeInstrument) > 0 {
		m["exclude_instrument"] = buildServicesYAML(b.args.Discovery.ExcludeInstrument)
	}
	if v := b.args.Discovery.ExcludeOTelInstrumentedServices; v != nil {
		m["exclude_otel_instrumented_services"] = *v
	}
	if b.args.Discovery.ExcludeOtelInstrumentedServicesSpanMetrics {
		m["exclude_otel_instrumented_services_span_metrics"] = true
	}
	if len(b.args.Discovery.ExcludeServices) > 0 {
		m["exclude_services"] = buildServicesYAML(b.args.Discovery.ExcludeServices)
	}
	if v := b.args.Discovery.ExcludedLinuxSystemPaths; len(v) > 0 {
		m["excluded_linux_system_paths"] = v
	}
	if len(b.args.Discovery.Instrument) > 0 {
		m["instrument"] = buildServicesYAML(b.args.Discovery.Instrument)
	}
	if v := b.args.Discovery.MinProcessAge; v != 0 {
		m["min_process_age"] = v.String()
	}
	if v := b.args.Discovery.PollInterval; v != 0 {
		m["poll_interval"] = v.String()
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.Discovery.RouteHarvesterAdvanced.JavaHarvestDelay; v != 0 {
			m1["java_harvest_delay"] = v.String()
		}
		if len(m1) > 0 {
			m["route_harvester_advanced"] = m1
		}
	}
	if v := b.args.Discovery.RouteHarvesterTimeout; v != 0 {
		m["route_harvester_timeout"] = v.String()
	}
	if len(b.args.Discovery.Services) > 0 {
		m["services"] = buildServicesYAML(b.args.Discovery.Services)
	}
	if b.args.Discovery.SkipGoSpecificTracers {
		m["skip_go_specific_tracers"] = true
	}
	if len(b.args.Discovery.Survey) > 0 {
		m["survey"] = buildServicesYAML(b.args.Discovery.Survey)
	}
	if len(m) > 0 {
		config["discovery"] = m
	}
}

// addEbpfConfig adds ebpf configuration.
func (b *builder) addEbpfConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := b.args.EBPF.BatchLength; v != 0 {
		m["batch_length"] = v
	}
	if v := b.args.EBPF.BatchTimeout; v != 0 {
		m["batch_timeout"] = v.String()
	}
	if b.args.EBPF.BpfDebug {
		m["bpf_debug"] = true
	}
	if v := b.args.EBPF.BpfFsPath; v != "" {
		m["bpf_fs_path"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.EBPF.BufferSizes.Http; v != 0 {
			m1["http"] = v
		}
		if v := b.args.EBPF.BufferSizes.Kafka; v != 0 {
			m1["kafka"] = v
		}
		if v := b.args.EBPF.BufferSizes.Mssql; v != 0 {
			m1["mssql"] = v
		}
		if v := b.args.EBPF.BufferSizes.Mysql; v != 0 {
			m1["mysql"] = v
		}
		if v := b.args.EBPF.BufferSizes.Postgres; v != 0 {
			m1["postgres"] = v
		}
		if v := b.args.EBPF.BufferSizes.Tcp; v != 0 {
			m1["tcp"] = v
		}
		if len(m1) > 0 {
			m["buffer_sizes"] = m1
		}
	}
	if v := b.args.EBPF.ContextPropagation; v != "" {
		m["context_propagation"] = v
	}
	if v := b.args.EBPF.CouchbaseDbCacheSize; v != 0 {
		m["couchbase_db_cache_size"] = v
	}
	if b.args.EBPF.DisableBlackBoxCp {
		m["disable_black_box_cp"] = true
	}
	if v := b.args.EBPF.DnsRequestTimeout; v != 0 {
		m["dns_request_timeout"] = v.String()
	}
	if v := b.args.EBPF.ForceBpfMapReader; v != "" {
		m["force_bpf_map_reader"] = v
	}
	if b.args.EBPF.HeuristicSQLDetect {
		m["heuristic_sql_detect"] = true
	}
	if b.args.EBPF.HighRequestVolume {
		m["high_request_volume"] = true
	}
	if v := b.args.EBPF.HTTPRequestTimeout; v != 0 {
		m["http_request_timeout"] = v.String()
	}
	if v := b.args.EBPF.InstrumentCuda; v != 0 {
		m["instrument_cuda"] = v
	}
	if v := b.args.EBPF.KafkaTopicUuidCacheSize; v != 0 {
		m["kafka_topic_uuid_cache_size"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.EBPF.LogEnricher.AsyncWriterChannelLen; v != 0 {
			m1["async_writer_channel_len"] = v
		}
		if v := b.args.EBPF.LogEnricher.AsyncWriterWorkers; v != 0 {
			m1["async_writer_workers"] = v
		}
		if v := b.args.EBPF.LogEnricher.CacheSize; v != 0 {
			m1["cache_size"] = v
		}
		if v := b.args.EBPF.LogEnricher.CacheTtl; v != 0 {
			m1["cache_ttl"] = v.String()
		}
		{
			list2 := make([]map[string]interface{}, 0, len(b.args.EBPF.LogEnricher.Services))
			for _, item2 := range b.args.EBPF.LogEnricher.Services {
				m2 := make(map[string]interface{})
				if len(item2.Service) > 0 {
					m2["service"] = buildServicesYAML(item2.Service)
				}
				if len(m2) > 0 {
					list2 = append(list2, m2)
				}
			}
			if len(list2) > 0 {
				m1["services"] = list2
			}
		}
		if len(m1) > 0 {
			m["log_enricher"] = m1
		}
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.EBPF.MapsConfig.GlobalScaleFactor; v != 0 {
			m1["global_scale_factor"] = v
		}
		if len(m1) > 0 {
			m["maps_config"] = m1
		}
	}
	if v := b.args.EBPF.MaxTransactionTime; v != 0 {
		m["max_transaction_time"] = v.String()
	}
	if v := b.args.EBPF.MongoRequestsCacheSize; v != 0 {
		m["mongo_requests_cache_size"] = v
	}
	if v := b.args.EBPF.MssqlPreparedStatementsCacheSize; v != 0 {
		m["mssql_prepared_statements_cache_size"] = v
	}
	if v := b.args.EBPF.MysqlPreparedStatementsCacheSize; v != 0 {
		m["mysql_prepared_statements_cache_size"] = v
	}
	if b.args.EBPF.OverrideBpfloopEnabled {
		m["override_bpfloop_enabled"] = true
	}
	{
		m1 := make(map[string]interface{})
		{
			m2 := make(map[string]interface{})
			{
				m3 := make(map[string]interface{})
				if b.args.EBPF.PayloadExtraction.HTTP.Aws.Enabled {
					m3["enabled"] = true
				}
				if len(m3) > 0 {
					m2["aws"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if b.args.EBPF.PayloadExtraction.HTTP.Elasticsearch.Enabled {
					m3["enabled"] = true
				}
				if len(m3) > 0 {
					m2["elasticsearch"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if b.args.EBPF.PayloadExtraction.HTTP.Enrichment.Enabled {
					m3["enabled"] = true
				}
				{
					m4 := make(map[string]interface{})
					{
						m5 := make(map[string]interface{})
						if v := b.args.EBPF.PayloadExtraction.HTTP.Enrichment.Policy.DefaultAction.Body; v != "" {
							m5["body"] = v
						}
						if v := b.args.EBPF.PayloadExtraction.HTTP.Enrichment.Policy.DefaultAction.Headers; v != "" {
							m5["headers"] = v
						}
						if len(m5) > 0 {
							m4["default_action"] = m5
						}
					}
					if v := b.args.EBPF.PayloadExtraction.HTTP.Enrichment.Policy.ObfuscationString; v != "" {
						m4["obfuscation_string"] = v
					}
					if len(m4) > 0 {
						m3["policy"] = m4
					}
				}
				{
					list4 := make([]map[string]interface{}, 0, len(b.args.EBPF.PayloadExtraction.HTTP.Enrichment.Rules))
					for _, item4 := range b.args.EBPF.PayloadExtraction.HTTP.Enrichment.Rules {
						m4 := make(map[string]interface{})
						if v := item4.Action; v != "" {
							m4["action"] = v
						}
						{
							m5 := make(map[string]interface{})
							if item4.Match.CaseSensitive {
								m5["case_sensitive"] = true
							}
							if v := item4.Match.Methods; len(v) > 0 {
								m5["methods"] = v
							}
							if v := item4.Match.ObfuscationJsonPaths; len(v) > 0 {
								m5["obfuscation_json_paths"] = v
							}
							if v := item4.Match.Patterns; len(v) > 0 {
								m5["patterns"] = v
							}
							if v := item4.Match.UrlPathPatterns; len(v) > 0 {
								m5["url_path_patterns"] = v
							}
							if len(m5) > 0 {
								m4["match"] = m5
							}
						}
						if v := item4.Scope; v != "" {
							m4["scope"] = v
						}
						if v := item4.Type; v != "" {
							m4["type"] = v
						}
						if len(m4) > 0 {
							list4 = append(list4, m4)
						}
					}
					if len(list4) > 0 {
						m3["rules"] = list4
					}
				}
				if len(m3) > 0 {
					m2["enrichment"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.OpenAI.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["openai"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.Anthropic.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["anthropic"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.Gemini.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["gemini"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.Bedrock.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["bedrock"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.Embedding.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["embedding"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.Mcp.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["mcp"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.Qwen.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["qwen"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.Rerank.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["rerank"] = m4
					}
				}
				{
					m4 := make(map[string]interface{})
					if b.args.EBPF.PayloadExtraction.HTTP.Retrieval.Enabled {
						m4["enabled"] = true
					}
					if len(m4) > 0 {
						m3["retrieval"] = m4
					}
				}
				if len(m3) > 0 {
					m2["genai"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if b.args.EBPF.PayloadExtraction.HTTP.Graphql.Enabled {
					m3["enabled"] = true
				}
				if len(m3) > 0 {
					m2["graphql"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if b.args.EBPF.PayloadExtraction.HTTP.Jsonrpc.Enabled {
					m3["enabled"] = true
				}
				if len(m3) > 0 {
					m2["jsonrpc"] = m3
				}
			}
			{
				m3 := make(map[string]interface{})
				if b.args.EBPF.PayloadExtraction.HTTP.Sqlpp.Enabled {
					m3["enabled"] = true
				}
				if v := b.args.EBPF.PayloadExtraction.HTTP.Sqlpp.EndpointPatterns; len(v) > 0 {
					m3["endpoint_patterns"] = v
				}
				if len(m3) > 0 {
					m2["sqlpp"] = m3
				}
			}
			if len(m2) > 0 {
				m1["http"] = m2
			}
		}
		if len(m1) > 0 {
			m["payload_extraction"] = m1
		}
	}
	if v := b.args.EBPF.PostgresPreparedStatementsCacheSize; v != 0 {
		m["postgres_prepared_statements_cache_size"] = v
	}
	if b.args.EBPF.ProtocolDebug {
		m["protocol_debug_print"] = true
	}
	{
		m1 := make(map[string]interface{})
		if b.args.EBPF.RedisDbCache.Enabled {
			m1["enabled"] = true
		}
		if v := b.args.EBPF.RedisDbCache.MaxSize; v != 0 {
			m1["max_size"] = v
		}
		if len(m1) > 0 {
			m["redis_db_cache"] = m1
		}
	}
	if v := b.args.EBPF.StatsWakeupDataBytes; v != 0 {
		m["stats_wakeup_data_bytes"] = v
	}
	if b.args.EBPF.TrackRequestHeaders {
		m["track_request_headers"] = true
	}
	if v := b.args.EBPF.TrafficControlBackend; v != "" {
		m["traffic_control_backend"] = v
	}
	if v := b.args.EBPF.WakeupLen; v != 0 {
		m["wakeup_len"] = v
	}
	if len(m) > 0 {
		config["ebpf"] = m
	}
}

// addInjectorConfig adds injector configuration.
func (b *builder) addInjectorConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := b.args.Injector.EnabledSdks; len(v) > 0 {
		m["enabled_sdks"] = v
	}
	if len(b.args.Injector.ExcludeInstrument) > 0 {
		m["exclude_instrument"] = buildServicesYAML(b.args.Injector.ExcludeInstrument)
	}
	if v := b.args.Injector.ExporterOtlpEndpoint; v != "" {
		m["exporter_otlp_endpoint"] = v
	}
	if v := b.args.Injector.ExporterOtlpProtocol; v != "" {
		m["exporter_otlp_protocol"] = v
	}
	if v := b.args.Injector.ImageVersion; v != "" {
		m["image_version"] = v
	}
	if len(b.args.Injector.Instrument) > 0 {
		m["instrument"] = buildServicesYAML(b.args.Injector.Instrument)
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.Injector.OtelExportedSignals.Logs; v != nil {
			m1["logs"] = *v
		}
		if v := b.args.Injector.OtelExportedSignals.Metrics; v != nil {
			m1["metrics"] = *v
		}
		if v := b.args.Injector.OtelExportedSignals.Traces; v != nil {
			m1["traces"] = *v
		}
		if len(m1) > 0 {
			m["otel_exported_signals"] = m1
		}
	}
	{
		m1 := make(map[string]interface{})
		if b.args.Injector.Resources.AddK8sIpAttribute {
			m1["add_k8s_ip_attribute"] = true
		}
		if b.args.Injector.Resources.AddK8sUidAttributes {
			m1["add_k8s_uid_attributes"] = true
		}
		if v := b.args.Injector.Resources.Attributes; len(v) > 0 {
			m1["attributes"] = v
		}
		if b.args.Injector.Resources.UseK8sLabelsForResourceAttributes {
			m1["use_k8s_labels_for_resource_attributes"] = true
		}
		if len(m1) > 0 {
			m["resources"] = m1
		}
	}
	if v := b.args.Injector.TracePropagators; len(v) > 0 {
		m["trace_propagators"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.Injector.TraceSampler.Arg; v != "" {
			m1["arg"] = v
		}
		if v := b.args.Injector.TraceSampler.Name; v != "" {
			m1["name"] = v
		}
		if len(m1) > 0 {
			m["trace_sampler"] = m1
		}
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.Injector.Webhook.ExternalDeploymentName; v != "" {
			m1["external_deployment_name"] = v
		}
		if len(m1) > 0 {
			m["webhook"] = m1
		}
	}
	if b.args.Injector.DisableAutoRestart {
		m["disable_auto_restart"] = true
	}
	if len(m) > 0 {
		config["injector"] = m
	}
}

// addJavaagentConfig adds javaagent configuration.
func (b *builder) addJavaagentConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := b.args.Javaagent.AttachTimeout; v != 0 {
		m["attach_timeout"] = v.String()
	}
	if b.args.Javaagent.Debug {
		m["debug"] = true
	}
	if b.args.Javaagent.DebugInstrumentation {
		m["debug_instrumentation"] = true
	}
	if v := b.args.Javaagent.Enabled; v != nil {
		m["enabled"] = *v
	}
	if len(m) > 0 {
		config["javaagent"] = m
	}
}

// addJvmRuntimeMetricsConfig adds jvm_runtime_metrics configuration.
func (b *builder) addJvmRuntimeMetricsConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if b.args.JVMRuntimeMetrics.Enabled {
		m["enabled"] = true
	}
	if v := b.args.JVMRuntimeMetrics.SamplingInterval; v != 0 {
		m["sampling_interval"] = v.String()
	}
	if len(m) > 0 {
		config["jvm_runtime_metrics"] = m
	}
}

// addNodejsConfig adds nodejs configuration.
func (b *builder) addNodejsConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := b.args.Nodejs.Enabled; v != nil {
		m["enabled"] = *v
	}
	if len(m) > 0 {
		config["nodejs"] = m
	}
}

// addRoutesConfig adds routes configuration.
func (b *builder) addRoutesConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := b.args.Routes.IgnoredEvents; v != "" {
		m["ignore_mode"] = v
	}
	if v := b.args.Routes.IgnorePatterns; len(v) > 0 {
		m["ignored_patterns"] = v
	}
	if v := b.args.Routes.MaxPathSegmentCardinality; v != 0 {
		m["max_path_segment_cardinality"] = v
	}
	if v := b.args.Routes.Patterns; len(v) > 0 {
		m["patterns"] = v
	}
	if v := b.args.Routes.Unmatch; v != "" {
		m["unmatched"] = v
	}
	if v := b.args.Routes.WildcardChar; v != "" {
		m["wildcard_char"] = v
	}
	if len(m) > 0 {
		config["routes"] = m
	}
}

// addStatsConfig adds stats configuration.
func (b *builder) addStatsConfig(config map[string]interface{}) {
	m := make(map[string]interface{})
	if v := b.args.Stats.AgentIP; v != "" {
		m["agent_ip"] = v
	}
	if v := b.args.Stats.AgentIPIface; v != "" {
		m["agent_ip_iface"] = v
	}
	if v := b.args.Stats.AgentIPType; v != "" {
		m["agent_ip_type"] = v
	}
	if v := b.args.Stats.CIDRs; len(v) > 0 {
		m["cidrs"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.Stats.GeoIp.CacheExpiry; v != 0 {
			m1["cache_expiry"] = v.String()
		}
		if v := b.args.Stats.GeoIp.CacheLen; v != 0 {
			m1["cache_len"] = v
		}
		{
			m2 := make(map[string]interface{})
			if v := b.args.Stats.GeoIp.Ipinfo.Path; v != "" {
				m2["path"] = v
			}
			if len(m2) > 0 {
				m1["ipinfo"] = m2
			}
		}
		{
			m2 := make(map[string]interface{})
			if v := b.args.Stats.GeoIp.Maxmind.AsnPath; v != "" {
				m2["asn_path"] = v
			}
			if v := b.args.Stats.GeoIp.Maxmind.CountryPath; v != "" {
				m2["country_path"] = v
			}
			if len(m2) > 0 {
				m1["maxmind"] = m2
			}
		}
		if len(m1) > 0 {
			m["geo_ip"] = m1
		}
	}
	if b.args.Stats.Print {
		m["print_stats"] = true
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.Stats.ReverseDns.CacheExpiry; v != 0 {
			m1["cache_expiry"] = v.String()
		}
		if v := b.args.Stats.ReverseDns.CacheLen; v != 0 {
			m1["cache_len"] = v
		}
		if v := b.args.Stats.ReverseDns.Type; v != "" {
			m1["type"] = v
		}
		if len(m1) > 0 {
			m["reverse_dns"] = m1
		}
	}
	if len(m) > 0 {
		config["stats"] = m
	}
}

// addGeneratedConfig invokes every generated section translation.
func (b *builder) addGeneratedConfig(config map[string]interface{}) {
	b.addDiscoveryConfig(config)
	b.addEbpfConfig(config)
	b.addInjectorConfig(config)
	b.addJavaagentConfig(config)
	b.addJvmRuntimeMetricsConfig(config)
	b.addNodejsConfig(config)
	b.addRoutesConfig(config)
	b.addStatsConfig(config)
}

// fillPrometheusExportConfig fills m with prometheus_export fields from metrics.
func (b *builder) fillPrometheusExportConfig(m map[string]interface{}) {
	if v := b.args.Metrics.Features; len(v) > 0 {
		m["features"] = v
	}
	if v := b.args.Metrics.Instrumentations; len(v) > 0 {
		m["instrumentations"] = v
	}
	if b.args.Metrics.AllowServiceGraphSelfReferences {
		m["allow_service_graph_self_references"] = true
	}
	if v := b.args.Metrics.ExtraResourceLabels; len(v) > 0 {
		m["extra_resource_attributes"] = v
	}
	if v := b.args.Metrics.ExtraSpanResourceLabels; len(v) > 0 {
		m["extra_span_resource_attributes"] = v
	}
	if b.args.Metrics.NativeHistograms {
		m["native_histograms"] = true
	}
	if v := b.args.Metrics.ExemplarFilter; v != "" {
		m["exemplar_filter"] = v
	}
	if v := b.args.Metrics.TTL; v != 0 {
		m["ttl"] = v.String()
	}
}

// fillNetworkConfig fills m with network fields from metrics.network.
func (b *builder) fillNetworkConfig(m map[string]interface{}) {
	if v := b.args.Metrics.Network.AgentIP; v != "" {
		m["agent_ip"] = v
	}
	if v := b.args.Metrics.Network.AgentIPIface; v != "" {
		m["agent_ip_iface"] = v
	}
	if v := b.args.Metrics.Network.AgentIPType; v != "" {
		m["agent_ip_type"] = v
	}
	if v := b.args.Metrics.Network.CacheActiveTimeout; v != 0 {
		m["cache_active_timeout"] = v.String()
	}
	if v := b.args.Metrics.Network.CacheMaxFlows; v != 0 {
		m["cache_max_flows"] = v
	}
	if v := b.args.Metrics.Network.CIDRs; len(v) > 0 {
		m["cidrs"] = v
	}
	if v := b.args.Metrics.Network.Deduper; v != "" {
		m["deduper"] = v
	}
	if v := b.args.Metrics.Network.DeduperFCTTL; v != 0 {
		m["deduper_fc_ttl"] = v.String()
	}
	if v := b.args.Metrics.Network.Direction; v != "" {
		m["direction"] = v
	}
	if b.args.Metrics.Network.Enable {
		m["enable"] = true
	}
	if v := b.args.Metrics.Network.ExcludeInterfaces; len(v) > 0 {
		m["exclude_interfaces"] = v
	}
	if v := b.args.Metrics.Network.ExcludeProtocols; len(v) > 0 {
		m["exclude_protocols"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.Metrics.Network.GeoIp.CacheExpiry; v != 0 {
			m1["cache_expiry"] = v.String()
		}
		if v := b.args.Metrics.Network.GeoIp.CacheLen; v != 0 {
			m1["cache_len"] = v
		}
		{
			m2 := make(map[string]interface{})
			if v := b.args.Metrics.Network.GeoIp.Ipinfo.Path; v != "" {
				m2["path"] = v
			}
			if len(m2) > 0 {
				m1["ipinfo"] = m2
			}
		}
		{
			m2 := make(map[string]interface{})
			if v := b.args.Metrics.Network.GeoIp.Maxmind.AsnPath; v != "" {
				m2["asn_path"] = v
			}
			if v := b.args.Metrics.Network.GeoIp.Maxmind.CountryPath; v != "" {
				m2["country_path"] = v
			}
			if len(m2) > 0 {
				m1["maxmind"] = m2
			}
		}
		if len(m1) > 0 {
			m["geo_ip"] = m1
		}
	}
	if v := b.args.Metrics.Network.GuessPorts; v != "" {
		m["guess_ports"] = v
	}
	if v := b.args.Metrics.Network.Interfaces; len(v) > 0 {
		m["interfaces"] = v
	}
	if v := b.args.Metrics.Network.ListenInterfaces; v != "" {
		m["listen_interfaces"] = v
	}
	if v := b.args.Metrics.Network.ListenPollPeriod; v != 0 {
		m["listen_poll_period"] = v.String()
	}
	if b.args.Metrics.Network.PrintFlows {
		m["print_flows"] = true
	}
	if v := b.args.Metrics.Network.Protocols; len(v) > 0 {
		m["protocols"] = v
	}
	{
		m1 := make(map[string]interface{})
		if v := b.args.Metrics.Network.ReverseDns.CacheExpiry; v != 0 {
			m1["cache_expiry"] = v.String()
		}
		if v := b.args.Metrics.Network.ReverseDns.CacheLen; v != 0 {
			m1["cache_len"] = v
		}
		if v := b.args.Metrics.Network.ReverseDns.Type; v != "" {
			m1["type"] = v
		}
		if len(m1) > 0 {
			m["reverse_dns"] = m1
		}
	}
	if v := b.args.Metrics.Network.Sampling; v != 0 {
		m["sampling"] = v
	}
	if v := b.args.Metrics.Network.Source; v != "" {
		m["source"] = v
	}
}

// fillAttributeFamiliesConfig builds a YAML map keyed by the "attr" field.
func fillAttributeFamiliesConfig(m map[string]interface{}, items AttributeFamilies) {
	for _, item := range items {
		sub := make(map[string]interface{})
		if v := item.Equals; v != nil {
			sub["equals"] = *v
		}
		if v := item.GreaterEquals; v != nil {
			sub["greater_equals"] = *v
		}
		if v := item.GreaterThan; v != nil {
			sub["greater_than"] = *v
		}
		if v := item.LessEquals; v != nil {
			sub["less_equals"] = *v
		}
		if v := item.LessThan; v != nil {
			sub["less_than"] = *v
		}
		if v := item.Match; v != "" {
			sub["match"] = v
		}
		if v := item.NotEquals; v != nil {
			sub["not_equals"] = *v
		}
		if v := item.NotMatch; v != "" {
			sub["not_match"] = v
		}
		if len(sub) > 0 {
			m[item.Attr] = sub
		}
	}
}

// fillSelectionsConfig builds a YAML map keyed by the "attr" field.
func fillSelectionsConfig(m map[string]interface{}, items Selections) {
	for _, item := range items {
		sub := make(map[string]interface{})
		if v := item.Exclude; len(v) > 0 {
			sub["exclude"] = v
		}
		if v := item.Include; len(v) > 0 {
			sub["include"] = v
		}
		if len(sub) > 0 {
			m[item.Section] = sub
		}
	}
}

func buildServicesYAML(items Services) []map[string]interface{} {
	result := make([]map[string]interface{}, 0, len(items))
	for _, item := range items {
		m := make(map[string]interface{})
		if v := item.CmdArgs; v != "" {
			m["cmd_args"] = v
		}
		if item.ContainersOnly {
			m["containers_only"] = true
		}
		if v := item.Path; v != "" {
			m["exe_path"] = v
		}
		if v := item.ExportModes; len(v) > 0 {
			m["exports"] = v
		}
		if v := item.Kubernetes.DaemonSetName; v != "" {
			m["k8s_daemonset_name"] = v
		}
		if v := item.Kubernetes.DeploymentName; v != "" {
			m["k8s_deployment_name"] = v
		}
		if v := item.Kubernetes.Namespace; v != "" {
			m["k8s_namespace"] = v
		}
		if v := item.Kubernetes.OwnerName; v != "" {
			m["k8s_owner_name"] = v
		}
		if v := item.Kubernetes.PodAnnotations; len(v) > 0 {
			m["k8s_pod_annotations"] = v
		}
		if v := item.Kubernetes.PodLabels; len(v) > 0 {
			m["k8s_pod_labels"] = v
		}
		if v := item.Kubernetes.PodName; v != "" {
			m["k8s_pod_name"] = v
		}
		if v := item.Kubernetes.ReplicaSetName; v != "" {
			m["k8s_replicaset_name"] = v
		}
		if v := item.Kubernetes.StatefulSetName; v != "" {
			m["k8s_statefulset_name"] = v
		}
		if v := item.Languages; v != "" {
			m["languages"] = v
		}
		if v := item.Name; v != "" {
			m["name"] = v
		}
		if v := item.Namespace; v != "" {
			m["namespace"] = v
		}
		if v := item.OpenPorts; v != "" {
			m["open_ports"] = v
		}
		{
			m1 := make(map[string]interface{})
			if v := item.Sampler.Arg; v != "" {
				m1["arg"] = v
			}
			if v := item.Sampler.Name; v != "" {
				m1["name"] = v
			}
			if len(m1) > 0 {
				m["sampler"] = m1
			}
		}
		if len(m) > 0 {
			result = append(result, m)
		}
	}
	return result
}
