// Code generated by internal/component/beyla/ebpf/internal/config/gen/main.go; DO NOT EDIT.

package config

// instrumentationValues are the values Beyla's schema accepts at "MetricsConfig.instrumentations".
var instrumentationValues = []string{
	"*",
	"amqp",
	"couchbase",
	"dns",
	"genai",
	"gpu",
	"grpc",
	"http",
	"kafka",
	"memcached",
	"mongo",
	"mqtt",
	"nats",
	"redis",
	"sql",
	"sunrpc",
}

// validInstrumentation reports whether v is an accepted "MetricsConfig.instrumentations" value.
func validInstrumentation(v string) bool {
	for _, x := range instrumentationValues {
		if v == x {
			return true
		}
	}
	return false
}

// metricFeatureValues are the values Beyla's schema accepts at "Features".
var metricFeatureValues = []string{
	"*",
	"all",
	"application",
	"application_host",
	"application_jvm",
	"application_process",
	"application_runtime",
	"application_service_graph",
	"application_span",
	"application_span_otel",
	"application_span_sizes",
	"ebpf",
	"network",
	"network_flow_packets",
	"network_inter_zone",
	"stats",
	"stats_tcp_failed_connections",
	"stats_tcp_io",
	"stats_tcp_retransmits",
	"stats_tcp_rtt",
}

// validMetricFeature reports whether v is an accepted "Features" value.
func validMetricFeature(v string) bool {
	for _, x := range metricFeatureValues {
		if v == x {
			return true
		}
	}
	return false
}

// samplerNameValues are the values Beyla's schema accepts at "SamplerConfig.name".
var samplerNameValues = []string{
	"always_off",
	"always_on",
	"parentbased_always_off",
	"parentbased_always_on",
	"parentbased_traceidratio",
	"traceidratio",
}

// validSamplerName reports whether v is an accepted "SamplerConfig.name" value.
func validSamplerName(v string) bool {
	for _, x := range samplerNameValues {
		if v == x {
			return true
		}
	}
	return false
}

// tracePrinterValues are the values Beyla's schema accepts at "trace_printer".
var tracePrinterValues = []string{
	"counter",
	"disabled",
	"json",
	"json_indent",
	"text",
}

// validTracePrinter reports whether v is an accepted "trace_printer" value.
func validTracePrinter(v string) bool {
	for _, x := range tracePrinterValues {
		if v == x {
			return true
		}
	}
	return false
}
