services:
  mimir:
    image: grafana/mimir:2.10.4
    volumes:
      - ./configs/mimir:/etc/mimir-config
    entrypoint:
      - /bin/mimir
      - -config.file=/etc/mimir-config/mimir.yaml
    ports:
      - "9009:9009"
    networks:
      - integration-tests      
  
  tempo:
    image: grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./configs/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"    # tempo
      - "9095:9095"    # tempo grpc
      - "4319:4317"    # otlp grpc
      - "4320:4318"    # otlp http
      - "9411:9411"    # zipkin
    networks:
      - integration-tests

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - integration-tests

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - integration-tests

  kafka-gen:
    depends_on:
      - kafka
    build:
      dockerfile: ./internal/cmd/integration-tests/configs/kafka/Dockerfile
      context: ../../..
    networks:
      - integration-tests

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - integration-tests

  otel-gen:
    build:
      dockerfile: ./internal/cmd/integration-tests/configs/otel-gen/Dockerfile
      context: ../../..
    environment:
      - OTEL_EXPORTER_ENDPOINT=${OTEL_EXPORTER_ENDPOINT:-alloy-otlp-metrics:4318}
    networks:
      - integration-tests
    ports:
      - "8443:8443"

  prom-gen:
    build:
      dockerfile: ./internal/cmd/integration-tests/configs/prom-gen/Dockerfile
      context: ../../..
    ports:
      - "9001:9001"
    networks:
      - integration-tests

  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"
    networks:
      - integration-tests

  snmp-simulator:
    image: tandrup/snmpsim:v0.4
    container_name: snmpsim
    ports:
      - "161:161/udp"
    networks:
      - integration-tests

networks:
  integration-tests:
    driver: bridge
