package main

import (
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// ##################################################################################
// ################################### TEST SETUP ###################################
// ##################################################################################

// copyDir recursively copies a directory
func copyDir(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		relPath, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}

		dstPath := filepath.Join(dst, relPath)

		if info.IsDir() {
			return os.MkdirAll(dstPath, info.Mode())
		}

		return copyFile(path, dstPath)
	})
}

// copyFile copies a single file
func copyFile(src, dst string) error {
	srcFile, err := os.Open(src)
	if err != nil {
		return err
	}
	defer srcFile.Close()

	dstFile, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer dstFile.Close()

	_, err = io.Copy(dstFile, srcFile)
	if err != nil {
		return err
	}

	srcInfo, err := os.Stat(src)
	if err != nil {
		return err
	}

	return os.Chmod(dst, srcInfo.Mode())
}

// testEnv holds the test environment paths and directories
type testEnv struct {
	scriptDir string
	goModPath string
}

// setupTestEnv sets up the test environment with all necessary files and directories.
// It returns a testEnv struct with all the paths needed for the test.
func setupTestEnv(t *testing.T, yamlContent, goModContent string) *testEnv {
	t.Helper()

	tmpDir := t.TempDir()
	scriptDir := filepath.Join(tmpDir, "tools", "sync-module-dependencies")
	if err := os.MkdirAll(scriptDir, 0755); err != nil {
		t.Fatalf("Failed to create script directory: %v", err)
	}

	projectRoot := tmpDir

	// Create dependency-replacements.yaml
	yamlPath := filepath.Join(projectRoot, "dependency-replacements.yaml")
	if err := os.WriteFile(yamlPath, []byte(yamlContent), 0644); err != nil {
		t.Fatalf("Failed to write dependency-replacements.yaml: %v", err)
	}

	// Create replaces-mod.tpl template
	templateContent := `// BEGIN GENERATED REPLACES - DO NOT EDIT
// Generated by go generate - DO NOT EDIT MANUALLY
{{- range . }}
{{- if .Comment }}
// {{ .Comment }}
{{- end }}
replace {{ .Dependency }} => {{ .Replacement }}
{{ end -}}
// END GENERATED REPLACES

`
	templatePath := filepath.Join(scriptDir, "replaces-mod.tpl")
	if err := os.WriteFile(templatePath, []byte(templateContent), 0644); err != nil {
		t.Fatalf("Failed to write replaces-mod.tpl: %v", err)
	}

	// Create go.mod file (this is the target file we'll modify)
	goModPath := filepath.Join(projectRoot, "go.mod")
	if err := os.WriteFile(goModPath, []byte(goModContent), 0644); err != nil {
		t.Fatalf("Failed to write go.mod: %v", err)
	}

	// Get the original working directory before changing
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current working directory: %v", err)
	}

	// Copy go.mod and go.sum to the test script directory so go generate can resolve dependencies
	originalGoMod := filepath.Join(originalWd, "go.mod")
	originalGoSum := filepath.Join(originalWd, "go.sum")

	testGoMod := filepath.Join(scriptDir, "go.mod")
	testGoSum := filepath.Join(scriptDir, "go.sum")

	// Copy go.mod and go.sum
	goModData, err := os.ReadFile(originalGoMod)
	if err != nil {
		t.Fatalf("Failed to read original go.mod: %v", err)
	}
	if err := os.WriteFile(testGoMod, goModData, 0644); err != nil {
		t.Fatalf("Failed to copy go.mod to test directory: %v", err)
	}

	if goSumData, err := os.ReadFile(originalGoSum); err == nil {
		if err := os.WriteFile(testGoSum, goSumData, 0644); err != nil {
			t.Fatalf("Failed to copy go.sum to test directory: %v", err)
		}
	}

	// Copy the internal directory structure so imports can be resolved
	originalInternal := filepath.Join(originalWd, "internal")
	testInternal := filepath.Join(scriptDir, "internal")

	if err := copyDir(originalInternal, testInternal); err != nil {
		t.Fatalf("Failed to copy internal directory: %v", err)
	}

	// Copy generate.go
	originalGenerateGo := filepath.Join(originalWd, "generate.go")
	testGenerateGo := filepath.Join(scriptDir, "generate.go")
	if err := copyFile(originalGenerateGo, testGenerateGo); err != nil {
		t.Fatalf("Failed to copy generate.go: %v", err)
	}

	return &testEnv{
		scriptDir: scriptDir,
		goModPath: goModPath,
	}
}

// runGoGenerate runs `go generate` in the test environment
func runGoGenerate(t *testing.T, env *testEnv) {
	t.Helper()

	// Change to script directory to simulate running from there
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current working directory: %v", err)
	}
	defer os.Chdir(originalWd)

	if err := os.Chdir(env.scriptDir); err != nil {
		t.Fatalf("Failed to change to script directory: %v", err)
	}

	// Run go generate
	cmd := exec.Command("go", "generate")
	cmd.Dir = env.scriptDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Logf("go generate output: %s", string(output))
		t.Fatalf("Failed to run go generate: %v", err)
	}
}

// ##################################################################################
// ################################### E2E TESTS ####################################
// ##################################################################################

// TestE2E tests the full pipeline: generating replaces from YAML and applying them to go.mod
func TestE2E(t *testing.T) {
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current working directory: %v", err)
	}
	defer os.Chdir(originalWd)

	// Test-specific setup: YAML and go.mod content
	yamlContent := `modules:
  - name: test-module
    path: go.mod
    file_type: mod

replaces:
  - comment: Test replace for example.com/package
    dependency: example.com/package
    replacement: example.com/fork v1.0.0

  - comment: Another test replace
    dependency: github.com/test/dependency
    replacement: github.com/test/fork v1.0.0
`

	goModContent := `module test.example.com

go 1.21

require (
	example.com/package v0.1.0
	github.com/test/dependency v1.0.0
)
`

	// Set up test environment
	env := setupTestEnv(t, yamlContent, goModContent)

	// Run go generate
	runGoGenerate(t, env)

	// Verify go.mod was updated
	updatedGoModContent, err := os.ReadFile(env.goModPath)
	if err != nil {
		t.Fatalf("Failed to read updated go.mod: %v", err)
	}

	actualGoMod := strings.TrimSpace(string(updatedGoModContent))

	// Define expected go.mod content
	// Note: go mod tidy removes unused dependencies, so the require block is removed
	expectedGoMod := `module test.example.com

go 1.21

// BEGIN GENERATED REPLACES - DO NOT EDIT
// Generated by go generate - DO NOT EDIT MANUALLY
// Test replace for example.com/package
replace example.com/package => example.com/fork v1.0.0

// Another test replace
replace github.com/test/dependency => github.com/test/fork v1.0.0

// END GENERATED REPLACES`

	expectedGoMod = strings.TrimSpace(expectedGoMod)

	if actualGoMod != expectedGoMod {
		t.Errorf("go.mod content mismatch.\nExpected:\n%s\n\nActual:\n%s", expectedGoMod, actualGoMod)
	}
}

// TestE2E_UpdateExisting tests updating an existing generated block
func TestE2E_UpdateExisting(t *testing.T) {
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current working directory: %v", err)
	}
	defer os.Chdir(originalWd)

	// Test-specific setup: YAML and go.mod content with existing generated block
	yamlContent := `modules:
  - name: test-module
    path: go.mod
    file_type: mod

replaces:
  - comment: Updated replace
    dependency: example.com/package
    replacement: example.com/fork v1.1.0
`

	goModContent := `module test.example.com

go 1.21

require (
	example.com/package v0.1.0
)

// BEGIN GENERATED REPLACES - DO NOT EDIT
// Generated by go generate - DO NOT EDIT MANUALLY
// Old comment
replace example.com/package => example.com/fork v1.0.0
// END GENERATED REPLACES
`

	// Set up test environment
	env := setupTestEnv(t, yamlContent, goModContent)

	// Run go generate
	runGoGenerate(t, env)

	// Verify go.mod was updated
	updatedGoModContent, err := os.ReadFile(env.goModPath)
	if err != nil {
		t.Fatalf("Failed to read updated go.mod: %v", err)
	}

	actualGoMod := strings.TrimSpace(string(updatedGoModContent))

	// Define expected go.mod content
	// Note: go mod tidy removes unused dependencies, so the require block is removed
	// The old replace should be replaced with the new one
	expectedGoMod := `module test.example.com

go 1.21

// BEGIN GENERATED REPLACES - DO NOT EDIT
// Generated by go generate - DO NOT EDIT MANUALLY
// Updated replace
replace example.com/package => example.com/fork v1.1.0

// END GENERATED REPLACES`

	expectedGoMod = strings.TrimSpace(expectedGoMod)

	if actualGoMod != expectedGoMod {
		t.Errorf("go.mod content mismatch.\nExpected:\n%s\n\nActual:\n%s", expectedGoMod, actualGoMod)
	}
}
