  # BEGIN GENERATED REPLACES - DO NOT EDIT
  # Generated by go generate - DO NOT EDIT MANUALLY

replaces:
{{- range . }}
{{- if .Comment }}
  # {{ .Comment }}
{{- end }}
  - {{ .Dependency }} => {{ .Replacement }}
{{- end }}
  # END GENERATED REPLACES