// Code generated by alloy-generate-metadata. DO NOT EDIT.

package journal

import (
	"github.com/grafana/alloy/internal/component"
)

var metadata = component.Metadata{
	Platforms: []string{
		"linux",
	},
	Requirements: []component.Requirement{
		{
			Description: "To read from the systemd journal, the `alloy` user must be a member of the `adm` and `systemd-journal` groups. Without this group membership, the component starts without error but collects no journal entries.\n",
		},
	},
}
