// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Represents build and runtime information for an Alloy instance.
// Contains version control and build environment details.
type Alloy struct {
	// The Git branch from which this build was created
	Branch string `json:"branch"`
	// The timestamp of when this build was created
	BuildDate string `json:"buildDate"`
	// The user account that initiated this build
	BuildUser string `json:"buildUser"`
	// Whether the Alloy instance is up and running
	IsReady bool `json:"isReady"`
	// The Git commit hash from which this build was created
	Revision string `json:"revision"`
	// The semantic version of this Alloy build
	Version string `json:"version"`
}

// Health status of the component.
type Health struct {
	// Message of the health status.
	Message string `json:"message"`
	// Last updated time of the health status.
	LastUpdated time.Time `json:"lastUpdated"`
}

type Query struct {
}
