# This file was generated by formula-gen.
# See: https://github.com/grafana/alloy/blob/main/packaging/homebrew/formula-gen/README.md
class Alloy < Formula
  desc "Vendor-agnostic OpenTelemetry Collector distribution with programmable pipelines"
  homepage "https://grafana.com/docs/alloy/latest"
  version "{{.Version}}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "{{.BaseURL}}/{{.Tag}}/{{.Artifacts.Darwin.Arm64.Package}}"
      sha256 "{{.Artifacts.Darwin.Arm64.Checksum}}"
    end
    if Hardware::CPU.intel?
      url "{{.BaseURL}}/{{.Tag}}/{{.Artifacts.Darwin.Amd64.Package}}"
      sha256 "{{.Artifacts.Darwin.Amd64.Checksum}}"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "{{.BaseURL}}/{{.Tag}}/{{.Artifacts.Linux.Amd64.Package}}"
      sha256 "{{.Artifacts.Linux.Amd64.Checksum}}"
    end

    if Hardware::CPU.arm?
      url "{{.BaseURL}}/{{.Tag}}/{{.Artifacts.Linux.Arm64.Package}}"
      sha256 "{{.Artifacts.Linux.Arm64.Checksum}}"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "alloy-#{os}-#{arch}" => "alloy"
    (bin/"alloy").chmod 0755

    generate_completions_from_executable(bin/"alloy", shell_parameter_format: :cobra)

    # Create a config.alloy file with default Alloy configuration
    (buildpath/"config.alloy").write <<~EOS
      logging {
        level  = "info"
        format = "logfmt"
      }
    EOS

    pkgetc.install "config.alloy"

    # Create an empty config.env file for environment variables
    (buildpath/"config.env").write ""
    pkgetc.install "config.env"

    # Create an empty extra-args.txt file for extra command line arguments
    (buildpath/"extra-args.txt").write ""
    pkgetc.install "extra-args.txt"

    # Create a wrapper script to run Alloy using the config in config.alloy,
    # env vars in config.env, and extra args in extra-args.txt
    (buildpath/"alloy-wrapper").write <<~SH
      #!/usr/bin/env sh
      if [ -f "#{pkgetc}/config.env" ]; then
        set -a
        . "#{pkgetc}/config.env"
        set +a
      fi

      otel_mode=""
      case "$(printf '%s' "${ALLOY_OTEL_MODE:-}" | tr '[:upper:]' '[:lower:]')" in
        1 | true | yes | on ) otel_mode="1" ;;
      esac

      extra_args_file="#{pkgetc}/extra-args.txt"
      [ -n "$otel_mode" ] && extra_args_file="#{pkgetc}/otel-extra-args.txt"

      extra_args=""
      [ -f "$extra_args_file" ] && extra_args=$(cat "$extra_args_file")

      # Rotate the service log files.
      #
      # launchd (and systemd on Linux) open the service log files and pass them
      # to Alloy as stdout/stderr. Renaming a file doesn't work, because Alloy
      # keeps writing to the renamed file. Instead, the file is copied to a
      # backup and truncated in place (copytruncate).
      #
      # ALLOY_SERVICE_LOG_FILES is set by the service definition below, so
      # running the wrapper from a terminal doesn't touch the service log files.
      log_max_size_mb="${ALLOY_LOG_MAX_SIZE_MB:-10}"
      log_max_backups="${ALLOY_LOG_MAX_BACKUPS:-3}"
      log_check_interval="${ALLOY_LOG_CHECK_INTERVAL:-60}"

      rotate_log() {
        log_file="$1"
        [ -f "$log_file" ] || return 0
        size=$(wc -c < "$log_file" | tr -d ' ')
        [ "$size" -gt $((log_max_size_mb * 1024 * 1024)) ] || return 0

        i="$log_max_backups"
        while [ "$i" -gt 1 ]; do
          prev=$((i - 1))
          [ -f "$log_file.$prev" ] && mv -f "$log_file.$prev" "$log_file.$i"
          i="$prev"
        done
        cp -f "$log_file" "$log_file.1" && : > "$log_file"
      }

      log_files="${ALLOY_SERVICE_LOG_FILES:-}"
      if [ -n "$log_files" ] && [ "$log_max_size_mb" -gt 0 ] && [ "$log_max_backups" -gt 0 ]; then
        for f in $log_files; do rotate_log "$f"; done

        # $$ is the PID of this shell, which becomes Alloy after exec below.
        # The loop stops once Alloy has exited.
        alloy_pid=$$
        (
          while sleep "$log_check_interval" && kill -0 "$alloy_pid" 2>/dev/null; do
            for f in $log_files; do rotate_log "$f"; done
          done
        ) </dev/null &
      fi

      # extra_args is intentionally unquoted so a file with multiple arguments
      # word-splits into separate argv entries.
      if [ -n "$otel_mode" ]; then
        exec "#{opt_bin}/alloy" otel \
          --config="file:#{pkgetc}/config.yaml" \
          $extra_args
      else
        exec "#{opt_bin}/alloy" run \
          --storage.path="#{var}/lib/alloy/data" \
          $extra_args \
          "#{pkgetc}"
      fi
    SH

    bin.install "alloy-wrapper"
    mkdir_p (var/"lib/alloy/data")
  end

  def caveats
    <<~EOS
      Alloy uses a set of files that you can customize before running:
        Configuration:
          #{pkgetc}/config.alloy
        Environment variables:
          #{pkgetc}/config.env
        Extra command line arguments:
          #{pkgetc}/extra-args.txt

      When running as a service, logs are written to:
        #{var}/log/alloy.log
        #{var}/log/alloy.err.log
      Log files are rotated when they exceed 10 MB, keeping 3 backups.
      To change this, set ALLOY_LOG_MAX_SIZE_MB and ALLOY_LOG_MAX_BACKUPS
      in #{pkgetc}/config.env. Set ALLOY_LOG_MAX_SIZE_MB=0 to disable rotation.

      To enable the OTel Engine:
        - Set "ALLOY_OTEL_MODE=1" in #{pkgetc}/config.env
        - Create collector config in #{pkgetc}/config.yaml
        - If necessary, create #{pkgetc}/otel-extra-args.txt to add command line arguments.
    EOS
  end

  service do
    run ["#{opt_bin}/alloy-wrapper"]
    keep_alive true
    log_path var/"log/alloy.log"
    error_log_path var/"log/alloy.err.log"
    # Log files rotated by alloy-wrapper. Must match log_path and error_log_path.
    environment_variables ALLOY_SERVICE_LOG_FILES: "#{var}/log/alloy.log #{var}/log/alloy.err.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/alloy --version")

    port = free_port

    (testpath/"config.alloy").write <<~EOS
      logging {
        level = "info"
      }
    EOS

    fork do
      exec bin/"alloy", "run", "#{testpath}/config.alloy",
        "--server.http.listen-addr=127.0.0.1:#{port}",
        "--storage.path=#{testpath}/data"
    end
    sleep 10

    output = shell_output("curl -s 127.0.0.1:#{port}/metrics")
    assert_match "alloy_build_info", output
  end
end
