---
kind: pipeline
name: Lint
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - apt-get update -y && apt-get install -y libsystemd-dev
  - make lint
  image: grafana/agent-build-image:0.32.0
  name: Lint
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Test dashboards
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-dashboards
  - ERR_MSG="Dashboard definitions are out of date. Please run 'make generate-dashboards'
    and commit changes!"
  - if [ ! -z "$(git status --porcelain)" ]; then echo $ERR_MSG >&2; exit 1; fi
  image: grafana/agent-build-image:0.32.0
  name: Regenerate dashboards
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Test
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make GO_TAGS="nodocker" test
  image: grafana/agent-build-image:0.32.0
  name: Run Go tests
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Test (Full)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - K8S_USE_DOCKER_NETWORK=1 make test
  image: grafana/agent-build-image:0.32.0
  name: Run Go tests
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  ref:
  - refs/heads/main
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: Test (Windows)
platform:
  arch: amd64
  os: windows
  version: "1809"
steps:
- commands:
  - go test -tags="nodocker,nonetwork" ./...
  image: grafana/agent-build-image:0.32.0-windows
  name: Run Go tests
trigger:
  ref:
  - refs/heads/main
type: docker
---
kind: pipeline
name: Check Linux container (grafana/agent)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make agent-image
  image: grafana/agent-build-image:0.32.0
  name: Build container
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  paths:
  - cmd/grafana-agent/Dockerfile
  - tools/ci/docker-containers
  ref:
  - refs/heads/main
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
kind: pipeline
name: Check Windows container (grafana/agent)
platform:
  arch: amd64
  os: windows
  version: "1809"
steps:
- commands:
  - '& "C:/Program Files/git/bin/bash.exe" ./tools/ci/docker-containers-windows agent'
  image: grafana/agent-build-image:0.32.0-windows
  name: Build container
  volumes:
  - name: docker
    path: //./pipe/docker_engine/
trigger:
  paths:
  - cmd/grafana-agent/Dockerfile.windows
  - tools/ci/docker-containers-windows
  ref:
  - refs/heads/main
type: docker
volumes:
- host:
    path: //./pipe/docker_engine/
  name: docker
---
kind: pipeline
name: Build agent (Linux amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets promtail_journal_enabled" GOOS=linux GOARCH=amd64 GOARM=
    make agent
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Linux arm64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets promtail_journal_enabled" GOOS=linux GOARCH=arm64 GOARM=
    make agent
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Linux ppc64le)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets promtail_journal_enabled" GOOS=linux GOARCH=ppc64le GOARM=
    make agent
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Linux s390x)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets promtail_journal_enabled" GOOS=linux GOARCH=s390x GOARM=
    make agent
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (macOS Intel)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets" GOOS=darwin GOARCH=amd64 GOARM= make agent
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (macOS Apple Silicon)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets" GOOS=darwin GOARCH=arm64 GOARM= make agent
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (Windows amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets" GOOS=windows GOARCH=amd64 GOARM= make agent
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent (FreeBSD amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets" GOOS=freebsd GOARCH=amd64 GOARM= make agent
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent-boringcrypto (Linux amd64 boringcrypto)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets promtail_journal_enabled" GOOS=linux GOARCH=amd64 GOARM=
    GOEXPERIMENT=boringcrypto make agent-boringcrypto
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent-boringcrypto (Linux arm64 boringcrypto)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets promtail_journal_enabled" GOOS=linux GOARCH=arm64 GOARM=
    GOEXPERIMENT=boringcrypto make agent-boringcrypto
  image: grafana/agent-build-image:0.32.0
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Build agent-windows-boringcrypto (Windows amd64)
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate-ui
  - GO_TAGS="builtinassets" GOOS=windows GOARCH=amd64 GOARM= GOEXPERIMENT=cngcrypto
    make agent-windows-boringcrypto
  image: grafana/agent-build-image:0.32.0-boringcrypto
  name: Build
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: Test Linux system packages
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - DOCKER_OPTS="" make dist/grafana-agent-linux-amd64
  - DOCKER_OPTS="" make test-packages
  image: grafana/agent-build-image:0.32.0
  name: Test Linux system packages
  volumes:
  - name: docker
    path: /var/run/docker.sock
trigger:
  paths:
  - packaging/**
  - Makefile
  ref:
  - refs/heads/main
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
---
get:
  name: app-id
  path: infra/data/ci/agent/githubapp
kind: secret
name: app_id
---
get:
  name: app-installation-id
  path: infra/data/ci/agent/githubapp
kind: secret
name: app_installation_id
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: docker_login
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: docker_password
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: dockerconfigjson
---
get:
  name: .dockerconfigjson
  path: infra/data/ci/gcr-admin
kind: secret
name: gcr_admin
---
get:
  name: passphrase
  path: infra/data/ci/packages-publish/gpg
kind: secret
name: gpg_passphrase
---
get:
  name: private-key
  path: infra/data/ci/packages-publish/gpg
kind: secret
name: gpg_private_key
---
get:
  name: public-key
  path: infra/data/ci/packages-publish/gpg
kind: secret
name: gpg_public_key
---
get:
  name: private-key
  path: infra/data/ci/agent/githubapp
kind: secret
name: private_key
---
get:
  name: app-id
  path: infra/data/ci/github/updater-app
kind: secret
name: updater_app_id
---
get:
  name: app-installation-id
  path: infra/data/ci/github/updater-app
kind: secret
name: updater_app_installation_id
---
get:
  name: private-key
  path: infra/data/ci/github/updater-app
kind: secret
name: updater_private_key
---
kind: signature
hmac: 9d5c94b8427eaa61069314281249efe1ba1c4a8a6d1c23e0088dff0c030d40a7

...
