#!/usr/bin/env bash
#
# This script builds and pushes cross-platform Docker containers. Maintainers
# should *not* run this locally since it pushes the containers.
#
# This script expects to be run from the repo root and has checks for running
# from a Drone trigger.
set -euxo pipefail

RELEASE_AGENT_IMAGE=grafana/agent
RELEASE_AGENTBORINGCRYPTO_IMAGE=grafana/agent-boringcrypto
DEVELOPMENT_AGENT_IMAGE=us-docker.pkg.dev/grafanalabs-dev/docker-alloy-dev/alloy
DEVELOPMENT_AGENTBORINGCRYPTO_IMAGE=us-docker.pkg.dev/grafanalabs-dev/docker-alloy-dev/alloy-boringcrypto

DEFAULT_AGENT_IMAGE=${RELEASE_AGENT_IMAGE}
DEFAULT_AGENTBORINGCRYPTO_IMAGE=${RELEASE_AGENTBORINGCRYPTO_IMAGE}

# Environment variables used throughout this script. These must be set
# otherwise bash will fail with an "unbound variable" error because of the `set
# -u` flag on the above line.
#
# If the environment variables are unset, the variables below default to an
# empty string.
export TARGET_CONTAINER=${1:-}
export DRONE_TAG=${DRONE_TAG:-}
export DEVELOPMENT=${DEVELOPMENT:-}

if [ -n "$DEVELOPMENT" ]; then
  DEFAULT_AGENT_IMAGE=${DEVELOPMENT_AGENT_IMAGE}
  DEFAULT_AGENTBORINGCRYPTO_IMAGE=${DEVELOPMENT_AGENTBORINGCRYPTO_IMAGE}
fi

export AGENT_IMAGE=${DEFAULT_AGENT_IMAGE}
export AGENT_BORINGCRYPTO_IMAGE=${DEFAULT_AGENTBORINGCRYPTO_IMAGE}

# We need to determine what version to assign to built binaries. If containers
# are being built from a Drone tag trigger, we force the version to come from the
# Drone tag name.
#
# Otherwise, we use the ./tools/image-tag script to determine the version.
if [ -n "$DRONE_TAG" ]; then
  VERSION=$DRONE_TAG
else
  VERSION=$(./tools/image-tag)
fi

# The TAG_VERSION is the version to use for the Docker tag. It is sanitized to
# force it to be a valid tag name; ./tools/image-tag can emit characters that
# are valid for semver but invalid for Docker tags, such as +.
TAG_VERSION=${VERSION//+/-}

# We also need to know which "branch tag" to update. Branch tags are used as a
# secondary tag for Docker containers. The branch tag is "latest" when being
# tagged from a stable release (i.e., not a release candidate).
#
# If we're not running from drone, we'll set the branch tag to match the
# version. This effectively acts as a no-op because it will tag the same Docker
# image twice.
if [ -n "$DRONE_TAG" ] && [[ "$DRONE_TAG" != *"-rc."* ]]; then
  BRANCH_TAG=latest
else
  BRANCH_TAG=$TAG_VERSION
fi

# Build all of our images.

export BUILD_PLATFORMS=linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
export BUILD_PLATFORMS_BORINGCRYPTO=linux/amd64,linux/arm64

case "$TARGET_CONTAINER" in
  agent)
    docker buildx build --push        \
      --platform $BUILD_PLATFORMS     \
      --build-arg RELEASE_BUILD=1     \
      --build-arg VERSION="$VERSION"  \
      -t "$AGENT_IMAGE:$TAG_VERSION"  \
      -t "$AGENT_IMAGE:$BRANCH_TAG"   \
      -f cmd/grafana-agent/Dockerfile \
      .
    ;;

  agent-boringcrypto)
    docker buildx build --push                    \
      --platform $BUILD_PLATFORMS_BORINGCRYPTO    \
      --build-arg RELEASE_BUILD=1                 \
      --build-arg VERSION="$VERSION"              \
      --build-arg GOEXPERIMENT=boringcrypto       \
      -t "$AGENT_BORINGCRYPTO_IMAGE:$TAG_VERSION" \
      -t "$AGENT_BORINGCRYPTO_IMAGE:$BRANCH_TAG"  \
      -f cmd/grafana-agent/Dockerfile             \
      .
    ;;

  *)
    echo "Usage: $0 agent|agent-boringcrypto"
    exit 1
    ;;
esac

