id: grafana/alloy/internal/component/common/net
"$defs":
  http:
    description: >-
      Configures the HTTP server that receives requests.
    type: object
    properties:
      conn_limit:
        description: >-
          Maximum number of simultaneous HTTP connections. Defaults to no limit.
        type: integer
        default: 0

      listen_address:
        description: >-
          Network address on which the server listens for new connections. Defaults to accepting all incoming connections.	
        type: string
        alloy:
          # TODO: We shouldn't have to set this explicitly.
          default_override: "\"\""

      listen_port:
        description: >-
          Port number on which the server listens for new connections.	
        type: integer
        default: 8080

      server_idle_timeout:
        description: >-
          Idle timeout for HTTP server.
        type: string
        default: "120s"
        alloy:
          type_override: "duration"

      server_read_timeout:
        description: >-
          Read timeout for HTTP server.
        type: string
        default: "30s"
        alloy:
          type_override: "duration"

      server_write_timeout:
        description: >-
          Write timeout for HTTP server.
        type: string
        default: "30s"
        alloy:
          type_override: "duration"
