// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/grafana/alloy/otel_engine

go 1.25.5

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.45.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.45.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v1.45.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.45.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.45.0
	go.opentelemetry.io/collector/connector/forwardconnector v0.139.0
	go.opentelemetry.io/collector/extension/zpagesextension v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.139.0
	github.com/grafana/alloy/extension/alloyengine v0.1.0
	go.opentelemetry.io/collector/receiver/otlpreceiver v0.139.0
	go.opentelemetry.io/collector/exporter/debugexporter v0.139.0
	go.opentelemetry.io/collector/exporter/nopexporter v0.139.0
	go.opentelemetry.io/collector/exporter/otlpexporter v0.139.0
	go.opentelemetry.io/collector/exporter/otlphttpexporter v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/zipkinexporter v0.139.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.139.0
	go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanprocessor v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.139.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.139.0
	go.opentelemetry.io/collector/otelcol v0.139.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)



























replace github.com/grafana/alloy => ../
replace github.com/grafana/alloy/syntax => ../syntax
replace github.com/grafana/alloy/extension/alloyengine => ../extension/alloyengine
replace go.opentelemetry.io/collector/featuregate => github.com/grafana/opentelemetry-collector/featuregate v0.0.0-20240325174506-2fd1623b2ca0
replace gopkg.in/yaml.v2 => github.com/rfratto/go-yaml v0.0.0-20211119180816-77389c3526dc
replace github.com/Azure/azure-sdk-for-go => github.com/Azure/azure-sdk-for-go v68.0.0+incompatible
replace github.com/Azure/azure-storage-blob-go => github.com/MasslessParticle/azure-storage-blob-go v0.14.1-0.20240322194317-344980fda573
replace github.com/gocql/gocql => github.com/grafana/gocql v0.0.0-20200605141915-ba5dc39ece85
replace github.com/grafana/regexp => github.com/grafana/regexp v0.0.0-20240518133315-a468a5bfb3bc
replace github.com/hashicorp/memberlist => github.com/grafana/memberlist v0.3.1-0.20220714140823-09ffed8adbbe
replace github.com/influxdata/go-syslog/v3 => github.com/leodido/go-syslog/v4 v4.3.0
replace github.com/thanos-io/objstore => github.com/grafana/objstore v0.0.0-20250210100727-533688b5600d
replace github.com/google/cadvisor => github.com/grafana/cadvisor v0.0.0-20260113212819-8e138474f7ff
replace github.com/prometheus-community/postgres_exporter => github.com/grafana/postgres_exporter v0.0.0-20250930111128-c8f6a9f4d363
replace github.com/prometheus/mysqld_exporter => github.com/grafana/mysqld_exporter v0.17.2-0.20250226152553-be612e3fdedd
replace github.com/prometheus/node_exporter => github.com/grafana/node_exporter v0.18.1-grafana-r01.0.20251024135609-318b01780c89
replace github.com/github/smimesign => github.com/grafana/smimesign v0.2.1-0.20220408144937-2a5adf3481d3
replace go.opentelemetry.io/obi => github.com/grafana/opentelemetry-ebpf-instrumentation v1.3.13
replace go.opentelemetry.io/ebpf-profiler => github.com/grafana/opentelemetry-ebpf-profiler v0.0.202550-0.20251216083346-f910fc4db23e
replace github.com/openshift/client-go => github.com/openshift/client-go v0.0.0-20251015124057-db0dee36e235
replace github.com/deneonet/benc => github.com/deneonet/benc v1.1.7
replace github.com/opencontainers/runc => github.com/opencontainers/runc v1.3.3
replace sigs.k8s.io/controller-runtime => sigs.k8s.io/controller-runtime v0.20.4
replace github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter => github.com/grafana/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.0.0-20260108134526-9817e6c361c9
