cluster:
  name: "alloy-example"

# Connection information for Grafana Cloud Services
grafanaCloud:
  # Fleet Management for fetching Alloy configuration remotely
  fleetManagement:
    url: "<set via terminal>"
    auth:
      type: basic
      username: "<set via terminal>"
      password: "<set via terminal>"

    # -- The frequency at which to poll the remote config server for updates.
    # @section -- Remote Configuration
    pollFrequency: 5m

    # -- Attributes to be added to all collectors when requesting configuration.
    # @section -- Remote Configuration
    extraAttributes: {}


collectors:
  alloy-daemon:
    image: # Need to use the one that understands the latest Beyla configs.
      repository: "grafana/alloy-dev"
      tag: "v1.10.0-devel-5126d5f"
    alloy:
      stabilityLevel: "experimental"
      logging:
        level: "debug"      
    controller:
      securityContext:
        # required for Beyla eBPF
        privileged: true 

    # required for Beyla eBPF
    hostPID: true
