name: 'Apply labels on a new issue'
on:
  issues:
    types: [opened]

permissions: read-all

jobs:
  apply-labels-on-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'grafana' }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
    
      - name: Run apply-component-labels
        run: ./.github/workflows/scripts/apply-component-labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: ${{ github.event.issue.body }}
