name: Check Windows build image

on:
  pull_request:
    paths:
      - 'build-tools/build-image/windows/**'

permissions:
  contents: read

jobs:
  check-windows-build-image:
    runs-on: windows-2022
    steps:
      - name: Ensure Docker is running (Docker issue workaround)
        id: docker-workaround
        run: |
          $dockerState = Get-Service -Name "docker"
          if ($dockerState.Status -ne "Running") {
            Start-Service -Name "docker"
          }

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Create test Windows build image
        uses: mr-smithers-excellent/docker-build-push@05b44e1dd9e03f78e8689bd1a61c750f17907ffe # v6.11
        with:
          image: grafana/alloy-build-image
          tags: latest
          registry: docker.io
          pushImage: false
          dockerfile: ./build-tools/build-image/windows/Dockerfile
