name: Check Windows build image

on:
  pull_request:
    paths:
      - 'tools/build-image/windows/**'

permissions:
  contents: read

jobs:
  check-windows-build-image:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create test Windows build image
        run: |
          docker build \
            --file ./tools/build-image/windows/Dockerfile \
            --tag grafana/alloy-build-image:latest \
            .
