name: Test Versioned Files
on: pull_request

permissions:
  contents: read

jobs:
  regenerate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Regenerate versioned files
        run: |
          make generate-versioned-files
          if ! git diff --exit-code; then
            echo "Newly generated versioned files differ from those checked in. Make sure to only update the templates manually and run 'make generate-versioned-files'!" >&2
            exit 1
          fi
