name: Create build images
on:
  push:
    tags:
      - build-image/v*

permissions:
  contents: read
  id-token: write

jobs:
  linux_build_image:
    name: Create a Linux build image
    runs-on: ubuntu-latest-8-cores
    steps:
    - name: Checkout code
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false

    - name: Remove unnecessary files
      run: |
          rm -rf /usr/share/dotnet
          rm -rf "$AGENT_TOOLSDIRECTORY"
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf /opt/hostedtoolcache

    - name: Get version from Git tag
      env:
        FULL_TAG: ${{ github.ref_name }}
      id: get_image_version
      run: echo "image_tag=${FULL_TAG##*/}" >> $GITHUB_OUTPUT

    - name: Login to Google Artifact Registry
      uses: grafana/shared-workflows/actions/login-to-gar@1f541877ceb22c7be7667d8a8df04984aeac9f9d # login-to-gar/v1.0.3
      with:
        registry: us-docker.pkg.dev

    - name: Setup QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

    - name: Create Linux build image
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        platforms: linux/amd64,linux/arm64
        context: ./build-tools/build-image
        push: true
        tags: us-docker.pkg.dev/grafanalabs-global/dockerhub-alloy-prod-mirror/alloy-build-image:${{ steps.get_image_version.outputs.image_tag }}
        build-args: |
          GO_RUNTIME=golang:1.26.7-alpine3.23
