name: Deploy pr preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    paths:
      - "docs/sources/**"

jobs:
  deploy-pr-preview:
    if: "!github.event.pull_request.head.repo.fork"
    uses: grafana/writers-toolkit/.github/workflows/deploy-preview.yml@e97bf199a578b923363e5cd7db079dad234aeb90 # main
    with:
      branch: ${{ github.head_ref }}
      event_number: ${{ github.event.number }}
      repo: alloy
      sha: ${{ github.event.pull_request.head.sha }}
      sources: |
        [
          {
            "index_file": "content/docs/alloy/_index.md",
            "relative_prefix": "/docs/alloy/latest/",
            "repo": "alloy",
            "source_directory": "docs/sources",
            "website_directory": "content/docs/alloy/latest"
          }
        ]
      title: ${{ github.event.pull_request.title }}
