name: Integration test (Windows service)
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'integration-tests/windows-service/**'
      - 'packaging/**'
      - 'internal/cmd/alloy-service/**'
      - 'internal/runtime/logging/**'
      - '.github/workflows/integration-test-windows-service.yml'

permissions:
  contents: read

jobs:
  integration_test_windows_service:
    name: Windows service integration test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup tools
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: v2026.5.18
          sha256: cfac593469d028d7ae5fe36e37bd7c59118b5238e92d8a876209578464f24a84
          install_args: go

      # TODO: Align the way we create the installer here, with the way it's created in for the official GitHub release.
      # Here we build it on Windows and install nsis explicitly, whereas there it's built on Linux on a container created with nsis beforehand.
      - name: Install NSIS
        run: choco install nsis -y
        shell: pwsh

      - name: Install NSIS AccessControl plugin
        run: |
          $nsisPath = "C:\Program Files (x86)\NSIS"
          $zipUrl = "https://nsis.sourceforge.io/mediawiki/images/4/4a/AccessControl.zip"
          $zipPath = "$env:TEMP\AccessControl.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing
          Expand-Archive -Path $zipPath -DestinationPath $env:TEMP\AccessControl -Force
          Copy-Item -Path "$env:TEMP\AccessControl\Plugins\*" -Destination "$nsisPath\Plugins\" -Recurse -Force
          New-Item -ItemType Directory -Path "$nsisPath\Plugins\x86-unicode" -Force
          Copy-Item -Path "$nsisPath\Plugins\i386-unicode\AccessControl.dll" -Destination "$nsisPath\Plugins\x86-unicode\"
        shell: pwsh

      - name: Add NSIS to PATH
        run: Add-Content -Path $env:GITHUB_PATH -Value "C:\Program Files (x86)\NSIS"
        shell: pwsh

      - name: Build installer and run Windows service integration test
        run: '& "C:/Program Files/git/bin/bash.exe" -c ''make integration-test-windows-service'''
