name: Lint
on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint_go:
    name: Lint Go
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
        cache: false

    - name: Lint alloy module
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        # renovate: datasource=github-releases packageName=golangci/golangci-lint
        version: v2.11.4

    - name: Lint syntax module
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        # renovate: datasource=github-releases packageName=golangci/golangci-lint
        version: v2.11.4
        working-directory: ./syntax/

    - name: Run custom linters
      run: make run-alloylint

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Shellcheck
      uses: Azbagheri/shell-linter@30a9cf3f6cf25c08fc98f10d7dc4167f7b5c0c00 # v0.8.0
      with:
        path: "\
          packaging,\
          production,\
          tools/ci,\
          tools/publish-release-assets.sh,\
          docs/sources/tutorials/assets\
          "

  lint_ui:
    name: Lint UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: internal/web/ui

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Set up Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: internal/web/ui/.nvmrc

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Format
      run: npm run format
