name: Shared Windows container publish workflow

on:
  workflow_call:
    inputs:
      img-name:
        required: true
        type: string
      push:
        required: false
        type: boolean
        default: true
      dev:
        required: false
        type: boolean
        default: false
      pr-number:
        required: false
        type: string
        default: ""
      ref:
        required: false
        type: string
        default: ""

permissions:
  contents: read
  id-token: write

jobs:
  publish_windows_container:
    name: Publish Alloy Windows container
    strategy:
      matrix:
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Ensure Docker is running (Docker issue workaround)
      id: docker-workaround
      run: |
        $dockerState = Get-Service -Name "docker"
        if ($dockerState.Status -ne "Running") {
          Start-Service -Name "docker"
        }

      # This step needs to run before "Checkout code".
      # That's because it generates a new file.
      # We don't want this file to end up in the repo directory.
      # Then "scripts/image-tag" would get confused because "git status" no longer reports a clean repo.
    - name: Login to Google Artifact Registry
      uses: grafana/shared-workflows/actions/login-to-gar@1f541877ceb22c7be7667d8a8df04984aeac9f9d # login-to-gar/v1.0.3
      with:
        registry: us-docker.pkg.dev

    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: false

    - name: Tag dev
      if: ${{ inputs.dev }}
      run: |
        & "C:/Program Files/git/bin/bash.exe" -c './scripts/tag-dev'

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
        cache: false

    - name: Get Go version from go.mod
      id: get_go_version
      # Use only the major and minor versions.
      # Don't use the patch number, because those docker images sometimes get deleted.
      run: |
        $go_version = go mod edit -json | ConvertFrom-Json | select -exp Go
        $go_version_split = $go_version.ToString().split(".")
        $go_short_version = $go_version_split[0] + "." + $go_version_split[1]
        "alloy_go_version=$go_short_version" >> $env:GITHUB_OUTPUT

    - name: Build and publish the container
      # TODO: Run "make alloy-image-windows" instead?
      run: |
        & "C:/Program Files/git/bin/bash.exe" -c 'PUSH_ALLOY_IMAGE=${SHOULD_PUSH_ALLOY_IMAGE} WINDOWS_VERSION=${{matrix.os}} ALLOY_GO_VERSION=${GO_VERSION} ./scripts/docker-containers-windows ${IMG_NAME}'
      env:
        SHOULD_PUSH_ALLOY_IMAGE: ${{ inputs.push }}
        IMG_NAME: ${{ inputs.img-name }}
        GO_VERSION: ${{ steps.get_go_version.outputs.alloy_go_version }}
        GITHUB_PR_NUMBER: ${{ inputs.pr-number }}
