name: Publish alloy release containers
# TODO: Reuse the config from publish-alloy-devel.yml
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish_windows_container:
    name: Publish Windows alloy container
    runs-on: windows-2022
    steps:
      # This step needs to run before "Checkout code".
      # That's because it generates a new file.
      # We don't want this file to end up in the repo directory.
      # Then "tools/image-tag" would get confused because "git status" no longer reports a clean repo.
    - name: Login to DockerHub (from vault)
      uses: grafana/shared-workflows/actions/dockerhub-login@dockerhub-login-v1.0.1

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: false

    - run: |
       & "C:/Program Files/git/bin/bash.exe" -c './tools/ci/docker-containers-windows alloy'
