name: Create Release Branch

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.0'

permissions:
  contents: write
  id-token: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub app secrets 🔐
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@f1614b210386ac420af6807a997ac7f6d96e477a # get-vault-secrets/v1.3.1
        with:
          export_env: false
          repo_secrets: |
            ALLOYBOT_APP_ID=alloybot:app_id
            ALLOYBOT_PRIVATE_KEY=alloybot:private_key

      - name: Generate token 🔐
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ fromJSON(steps.get-secrets.outputs.secrets).ALLOYBOT_APP_ID }}
          private-key: ${{ fromJSON(steps.get-secrets.outputs.secrets).ALLOYBOT_PRIVATE_KEY }}
          owner: grafana
          repositories: alloy

      - name: Checkout repository 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Set up Go 🏗️
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: tools/go.mod
          cache-dependency-path: tools/go.sum
          cache: false

      - name: Run create-release-branch tool 🌿
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: |
          cd tools
          go run ./release/create-release-branch --tag "${RELEASE_TAG}"
