name: Release Please

on:
  push:
    branches:
      - main
      - 'release/v*'

permissions:
  id-token: write

env:
  ALLOYBOT_APP_NAME: grafana-alloybot

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token 🔐
        uses: grafana/shared-workflows/actions/create-github-app-token@46f48da11e78ebdba7a8747ae456b11062fac83e # create-github-app-token/v0.3.1
        id: app-token
        with:
          github_app: ${{ env.ALLOYBOT_APP_NAME }}

      - name: Checkout repository 🛎️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Setup Node.js 🏗️
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: build-tools/release-please-runner/.nvmrc
          package-manager-cache: false

      - name: Install dependencies 📦
        working-directory: build-tools/release-please-runner
        run: npm ci --no-audit --no-fund

      - name: Run release-please 🚀
        working-directory: build-tools/release-please-runner
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO_URL: ${{ github.repository }}
          TARGET_BRANCH: ${{ github.ref_name }}
          CONFIG_FILE: release-please-config.json
          MANIFEST_FILE: .release-please-manifest.json
        run: node index.js
