name: Snyk Monitor Scanning
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-scan-ci:
    uses: grafana/security-github-actions/.github/workflows/snyk_monitor.yml@1252e245a5f014cf9bc606d3ebddef9d975f0ad2 # main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
