name: Snyk Monitor Scanning
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-scan-ci:
    uses: grafana/security-github-actions/.github/workflows/snyk_monitor.yml@c11b390d61fee8bdda402cf36090bb075a99e8c5 # main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
