name: Snyk Monitor Scanning
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-scan-ci:
    uses: grafana/security-github-actions/.github/workflows/snyk_monitor.yml@e784a0238161975161e123d6121d7bad18c2b793 # main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
