name: Test (Windows)
on:
  push:
    # TODO: Also run the tests when a Windows-specific features is changed.
    # For example, the Windows Exporter for Prometheus and Event Log tailers.
    branches:
      - main
  # TODO: Run the Windows tests for each PR?
  # For now we don't do it just because it takes time.
  pull_request:
    types: [labeled, opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  test_windows:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'os:windows') || github.event_name == 'push' || github.event_name == 'merge_group' }}
    name: Test (Windows)
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Setup tools
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        install_args: go

    - name: Test
      run: '& "C:/Program Files/git/bin/bash.exe" -c ''make GO_TAGS="nodocker nonetwork" test'''
