name: Test logging in to DockerHub
on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test_linux:
    name: Test login
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub (from vault)
      uses: grafana/shared-workflows/actions/dockerhub-login@dockerhub-login-v1.0.0
