name: Test (Full)
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test_linux:
    name: Test (Full)
    runs-on: ubuntu-latest-8-cores
    container:
      image: grafana/alloy-build-image:v0.1.33@sha256:dbdecbfbad6c9ed0b315a7a6da25ef066b795ffc57e887125333b1a352907155
      volumes:
        - /var/run/docker.sock
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Set ownership
      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

    - name: Setup tools
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        install_args: go

    - run: K8S_USE_DOCKER_NETWORK=1 make test
