name: Test Linux system packages
on:
  push:
    branches:
      - main
    paths:
    - packaging/**
    - internal/tools/packaging_test/**
    - Makefile
    - build-tools/make/*.mk

permissions:
  contents: read

jobs:
  test_linux_system_packages:
    name: Test Linux system packages
    runs-on: ubuntu-latest-8-cores
    container:
      image: grafana/alloy-build-image:v0.1.32@sha256:f9dd7a2db22b68d90f53fc190e5cd6a0b59dedd607e9d12dcb0182f1031f199d
      volumes:
        - /var/run/docker.sock
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Set ownership
      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

    - name: Setup tools
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        install_args: go

    - run: DOCKER_OPTS="" make dist/alloy-linux-amd64
    - run: DOCKER_OPTS="" make test-packages
