name: Test (Mac)
on:
  # Run tests on main just so the module and build cache can be saved and used
  # in PRs. This speeds up the time it takes to test PRs dramatically.
  # (More information on https://docs.github.com/en/enterprise-server@3.6/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test (Mac)
    strategy:
      matrix:
        platform: [macos-15-xlarge]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Setup tools
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        version: v2026.5.18
        sha256: 998428f820e22301bab9273cba8b4e59d05a40f77a9a8411d75b2de85fbb0335
        install_args: go

    - name: Cache Go modules and build
      uses: ./.github/actions/go-cache

    - name: Test
      run: CGO_LDFLAGS="-ld_classic $CGO_LDFLAGS" make GO_TAGS="nodocker" test

  cross-compile-mac-to-linux-nocgo:
    name: Verify mac-to-linux cross-compile # This is to maintain good developer experience on macOS
    runs-on: macos-15-xlarge
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Setup tools
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        version: v2026.5.18
        sha256: 998428f820e22301bab9273cba8b4e59d05a40f77a9a8411d75b2de85fbb0335
        install_args: go

    - run: cd collector && go build .
    - run: go build ./internal/component/pyroscope/util/internal/cmd/playground
