apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-gen
  template:
    metadata:
      labels:
        app: prom-gen
    spec:
      containers:
        - name: prom-gen
          image: prom-gen:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9001
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: prom-gen
  labels:
    app: prom-gen
spec:
  selector:
    app: prom-gen
  ports:
    - port: 9001
      targetPort: 9001
      name: metrics
