package stages

const (
	StageTypeJSON            = "json"
	StageTypeLogfmt          = "logfmt"
	StageTypeRegex           = "regex"
	StageTypeReplace         = "replace"
	StageTypeMetric          = "metrics"
	StageTypeLabel           = "labels"
	StageTypeLabelDrop       = "labeldrop"
	StageTypeTimestamp       = "timestamp"
	StageTypeOutput          = "output"
	StageTypeDocker          = "docker"
	StageTypeCRI             = "cri"
	StageTypeMatch           = "match"
	StageTypeTemplate        = "template"
	StageTypePipeline        = "pipeline"
	StageTypeTenant          = "tenant"
	StageTypeDrop            = "drop"
	StageTypeSampling        = "sampling"
	StageTypeLimit           = "limit"
	StageTypeMultiline       = "multiline"
	StageTypePack            = "pack"
	StageTypeLabelAllow      = "labelallow"
	StageTypeStaticLabels    = "static_labels"
	StageTypeDecolorize      = "decolorize"
	StageTypeEventLogMessage = "eventlogmessage"
	StageTypeGeoIP           = "geoip"
	// Deprecated. Renamed to `structured_metadata`. Will be removed after the migration.
	StageTypeNonIndexedLabels   = "non_indexed_labels"
	StageTypeStructuredMetadata = "structured_metadata"
)
